ALTER TABLE [dbo].[Nop_DiscountLimitation]
    ADD CONSTRAINT [Nop_DiscountLimitation_PK] PRIMARY KEY CLUSTERED ([DiscountLimitationID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

