ALTER TABLE [dbo].[ED_InterestedCustomer]
    ADD CONSTRAINT [PK_ED_InterestedCustomer] PRIMARY KEY CLUSTERED ([InterestedCustomerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

