ALTER TABLE [dbo].[ED_Topics]
    ADD CONSTRAINT [PK_ED_Topics] PRIMARY KEY CLUSTERED ([TopicId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

