ALTER TABLE [dbo].[ED_CarfaxLogDetail]
    ADD CONSTRAINT [PK_ED_CarfaxLogDetail] PRIMARY KEY CLUSTERED ([CarFax_logID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

