ALTER TABLE [dbo].[ED_EGear]
    ADD CONSTRAINT [PK_ED_EGear] PRIMARY KEY CLUSTERED ([eGearID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

