ALTER TABLE [dbo].[ED_City]
    ADD CONSTRAINT [PK_ED_City] PRIMARY KEY CLUSTERED ([CityId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

