ALTER TABLE [dbo].[ED_EManagement]
    ADD CONSTRAINT [PK_ED_EManagement] PRIMARY KEY CLUSTERED ([ManagementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

