ALTER TABLE [dbo].[ED_ExpertDocuments]
    ADD CONSTRAINT [PK_ED_ExpertDocuments] PRIMARY KEY CLUSTERED ([EDId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

