ALTER TABLE [dbo].[ED_ProductData]
    ADD CONSTRAINT [PK_ED_ProductData] PRIMARY KEY CLUSTERED ([VIN] ASC, [CustomerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

