ALTER TABLE [dbo].[ED_Faq]
    ADD CONSTRAINT [PK_ED_Faq] PRIMARY KEY CLUSTERED ([FaqId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

