ALTER TABLE [dbo].[ED_VehicleOptions]
    ADD CONSTRAINT [PK_ED_VehicleOptions] PRIMARY KEY CLUSTERED ([VehicleOptionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

