ALTER TABLE [dbo].[ED_Testimonials]
    ADD CONSTRAINT [PK_ED_Testimonials] PRIMARY KEY CLUSTERED ([TId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

