ALTER TABLE [dbo].[ED_SystemParameter]
    ADD CONSTRAINT [PK_Nop_ED_SystemParameter] PRIMARY KEY CLUSTERED ([ParameterID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

