//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 

using System;
using System.Linq;

#pragma warning disable 1591

namespace EdriveService.NADA_UsedCars {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsedCarsSoap", Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCars : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUsedCarOptionsTypedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarValueTypedwithOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarValueTypedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarsNoVINOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsedCars() {
            this.Url = global::EdriveService.Properties.Settings.Default.EdriveService_NADA_UsedCars_UsedCars;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUsedCarOptionsTypedCompletedEventHandler GetUsedCarOptionsTypedCompleted;
        
        /// <remarks/>
        public event GetUsedCarValueTypedwithOptionsCompletedEventHandler GetUsedCarValueTypedwithOptionsCompleted;
        
        /// <remarks/>
        public event GetUsedCarValueTypedCompletedEventHandler GetUsedCarValueTypedCompleted;
        
        /// <remarks/>
        public event GetUsedCarOptionsCompletedEventHandler GetUsedCarOptionsCompleted;
        
        /// <remarks/>
        public event GetUsedCarValueCompletedEventHandler GetUsedCarValueCompleted;
        
        /// <remarks/>
        public event GetUsedCarsCompletedEventHandler GetUsedCarsCompleted;
        
        /// <remarks/>
        public event GetUsedCarsNoVINCompletedEventHandler GetUsedCarsNoVINCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarOptionsTyped", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarOptionList GetUsedCarOptionsTyped(string UserID, string Password, string StyleID) {
            object[] results = this.Invoke("GetUsedCarOptionsTyped", new object[] {
                        UserID,
                        Password,
                        StyleID});
            return ((UsedCarOptionList)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarOptionsTypedAsync(string UserID, string Password, string StyleID) {
            this.GetUsedCarOptionsTypedAsync(UserID, Password, StyleID, null);
        }
        
        /// <remarks/>
        public void GetUsedCarOptionsTypedAsync(string UserID, string Password, string StyleID, object userState) {
            if ((this.GetUsedCarOptionsTypedOperationCompleted == null)) {
                this.GetUsedCarOptionsTypedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarOptionsTypedOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarOptionsTyped", new object[] {
                        UserID,
                        Password,
                        StyleID}, this.GetUsedCarOptionsTypedOperationCompleted, userState);
        }
        
        private void OnGetUsedCarOptionsTypedOperationCompleted(object arg) {
            if ((this.GetUsedCarOptionsTypedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarOptionsTypedCompleted(this, new GetUsedCarOptionsTypedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarValueTypedwithOptions", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarValueOption GetUsedCarValueTypedwithOptions(string UserID, string Password, string StyleID, string options, string mileage) {
            object[] results = this.Invoke("GetUsedCarValueTypedwithOptions", new object[] {
                        UserID,
                        Password,
                        StyleID,
                        options,
                        mileage});
            return ((UsedCarValueOption)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarValueTypedwithOptionsAsync(string UserID, string Password, string StyleID, string options, string mileage) {
            this.GetUsedCarValueTypedwithOptionsAsync(UserID, Password, StyleID, options, mileage, null);
        }
        
        /// <remarks/>
        public void GetUsedCarValueTypedwithOptionsAsync(string UserID, string Password, string StyleID, string options, string mileage, object userState) {
            if ((this.GetUsedCarValueTypedwithOptionsOperationCompleted == null)) {
                this.GetUsedCarValueTypedwithOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarValueTypedwithOptionsOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarValueTypedwithOptions", new object[] {
                        UserID,
                        Password,
                        StyleID,
                        options,
                        mileage}, this.GetUsedCarValueTypedwithOptionsOperationCompleted, userState);
        }
        
        private void OnGetUsedCarValueTypedwithOptionsOperationCompleted(object arg) {
            if ((this.GetUsedCarValueTypedwithOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarValueTypedwithOptionsCompleted(this, new GetUsedCarValueTypedwithOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarValueTyped", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarValue GetUsedCarValueTyped(string UserID, string Password, string StyleID, string options, string mileage) {
            object[] results = this.Invoke("GetUsedCarValueTyped", new object[] {
                        UserID,
                        Password,
                        StyleID,
                        options,
                        mileage});
            return ((UsedCarValue)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarValueTypedAsync(string UserID, string Password, string StyleID, string options, string mileage) {
            this.GetUsedCarValueTypedAsync(UserID, Password, StyleID, options, mileage, null);
        }
        
        /// <remarks/>
        public void GetUsedCarValueTypedAsync(string UserID, string Password, string StyleID, string options, string mileage, object userState) {
            if ((this.GetUsedCarValueTypedOperationCompleted == null)) {
                this.GetUsedCarValueTypedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarValueTypedOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarValueTyped", new object[] {
                        UserID,
                        Password,
                        StyleID,
                        options,
                        mileage}, this.GetUsedCarValueTypedOperationCompleted, userState);
        }
        
        private void OnGetUsedCarValueTypedOperationCompleted(object arg) {
            if ((this.GetUsedCarValueTypedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarValueTypedCompleted(this, new GetUsedCarValueTypedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarOptions", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetUsedCarOptions(string UserID, string Password, string StyleID) {
            object[] results = this.Invoke("GetUsedCarOptions", new object[] {
                        UserID,
                        Password,
                        StyleID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarOptionsAsync(string UserID, string Password, string StyleID) {
            this.GetUsedCarOptionsAsync(UserID, Password, StyleID, null);
        }
        
        /// <remarks/>
        public void GetUsedCarOptionsAsync(string UserID, string Password, string StyleID, object userState) {
            if ((this.GetUsedCarOptionsOperationCompleted == null)) {
                this.GetUsedCarOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarOptionsOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarOptions", new object[] {
                        UserID,
                        Password,
                        StyleID}, this.GetUsedCarOptionsOperationCompleted, userState);
        }
        
        private void OnGetUsedCarOptionsOperationCompleted(object arg) {
            if ((this.GetUsedCarOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarOptionsCompleted(this, new GetUsedCarOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarValue", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetUsedCarValue(string UserID, string Password, string StyleID, string Options, string Mileage) {
            object[] results = this.Invoke("GetUsedCarValue", new object[] {
                        UserID,
                        Password,
                        StyleID,
                        Options,
                        Mileage});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarValueAsync(string UserID, string Password, string StyleID, string Options, string Mileage) {
            this.GetUsedCarValueAsync(UserID, Password, StyleID, Options, Mileage, null);
        }
        
        /// <remarks/>
        public void GetUsedCarValueAsync(string UserID, string Password, string StyleID, string Options, string Mileage, object userState) {
            if ((this.GetUsedCarValueOperationCompleted == null)) {
                this.GetUsedCarValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarValueOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarValue", new object[] {
                        UserID,
                        Password,
                        StyleID,
                        Options,
                        Mileage}, this.GetUsedCarValueOperationCompleted, userState);
        }
        
        private void OnGetUsedCarValueOperationCompleted(object arg) {
            if ((this.GetUsedCarValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarValueCompleted(this, new GetUsedCarValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCars", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarResultSet GetUsedCars(string UserName, string Password, string VIN) {
            object[] results = this.Invoke("GetUsedCars", new object[] {
                        UserName,
                        Password,
                        VIN});
            return ((UsedCarResultSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarsAsync(string UserName, string Password, string VIN) {
            this.GetUsedCarsAsync(UserName, Password, VIN, null);
        }
        
        /// <remarks/>
        public void GetUsedCarsAsync(string UserName, string Password, string VIN, object userState) {
            if ((this.GetUsedCarsOperationCompleted == null)) {
                this.GetUsedCarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarsOperationCompleted);
            }
            this.InvokeAsync("GetUsedCars", new object[] {
                        UserName,
                        Password,
                        VIN}, this.GetUsedCarsOperationCompleted, userState);
        }
        
        private void OnGetUsedCarsOperationCompleted(object arg) {
            if ((this.GetUsedCarsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarsCompleted(this, new GetUsedCarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarsNoVIN", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarResultSet GetUsedCarsNoVIN(string UserName, string Password, string NewCarStyleIDs) {
            object[] results = this.Invoke("GetUsedCarsNoVIN", new object[] {
                        UserName,
                        Password,
                        NewCarStyleIDs});
            return ((UsedCarResultSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarsNoVINAsync(string UserName, string Password, string NewCarStyleIDs) {
            this.GetUsedCarsNoVINAsync(UserName, Password, NewCarStyleIDs, null);
        }
        
        /// <remarks/>
        public void GetUsedCarsNoVINAsync(string UserName, string Password, string NewCarStyleIDs, object userState) {
            if ((this.GetUsedCarsNoVINOperationCompleted == null)) {
                this.GetUsedCarsNoVINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarsNoVINOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarsNoVIN", new object[] {
                        UserName,
                        Password,
                        NewCarStyleIDs}, this.GetUsedCarsNoVINOperationCompleted, userState);
        }
        
        private void OnGetUsedCarsNoVINOperationCompleted(object arg) {
            if ((this.GetUsedCarsNoVINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarsNoVINCompleted(this, new GetUsedCarsNoVINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarOptionList {
        
        private System.Xml.XmlNode messageField;
        
        private UsedCarOptions[] optionListField;
        
        private string transactionIDField;
        
        private bool hasErrorField;
        
        private ErrorProfile errorField;
        
        /// <remarks/>
        public System.Xml.XmlNode Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public UsedCarOptions[] OptionList {
            get {
                return this.optionListField;
            }
            set {
                this.optionListField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarOptions {
        
        private int optionIDField;
        
        private string displayNameField;
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCar {
        
        private int highRetailField;
        
        private int lowRetailField;
        
        private int cityFuelLowField;
        
        private int cityFuelHighField;
        
        private int highwayFuelLowField;
        
        private int highwayFuelHighField;
        
        private int styleIDField;
        
        private int makeIDField;
        
        private int optionKeyIDField;
        
        private int modelIDField;
        
        private int c_ModelIDField;
        
        private int yearField;
        
        private string makeDisplayField;
        
        private string modelDisplayField;
        
        private string trimDisplayField;
        
        private UsedCarOptions[] usedCarOptionsField;
        
        private int mSRPField;
        
        private int averageRetailPriceField;
        
        private int averageTradeinPriceField;
        
        /// <remarks/>
        public int HighRetail {
            get {
                return this.highRetailField;
            }
            set {
                this.highRetailField = value;
            }
        }
        
        /// <remarks/>
        public int LowRetail {
            get {
                return this.lowRetailField;
            }
            set {
                this.lowRetailField = value;
            }
        }
        
        /// <remarks/>
        public int CityFuelLow {
            get {
                return this.cityFuelLowField;
            }
            set {
                this.cityFuelLowField = value;
            }
        }
        
        /// <remarks/>
        public int CityFuelHigh {
            get {
                return this.cityFuelHighField;
            }
            set {
                this.cityFuelHighField = value;
            }
        }
        
        /// <remarks/>
        public int HighwayFuelLow {
            get {
                return this.highwayFuelLowField;
            }
            set {
                this.highwayFuelLowField = value;
            }
        }
        
        /// <remarks/>
        public int HighwayFuelHigh {
            get {
                return this.highwayFuelHighField;
            }
            set {
                this.highwayFuelHighField = value;
            }
        }
        
        /// <remarks/>
        public int StyleID {
            get {
                return this.styleIDField;
            }
            set {
                this.styleIDField = value;
            }
        }
        
        /// <remarks/>
        public int MakeID {
            get {
                return this.makeIDField;
            }
            set {
                this.makeIDField = value;
            }
        }
        
        /// <remarks/>
        public int OptionKeyID {
            get {
                return this.optionKeyIDField;
            }
            set {
                this.optionKeyIDField = value;
            }
        }
        
        /// <remarks/>
        public int ModelID {
            get {
                return this.modelIDField;
            }
            set {
                this.modelIDField = value;
            }
        }
        
        /// <remarks/>
        public int C_ModelID {
            get {
                return this.c_ModelIDField;
            }
            set {
                this.c_ModelIDField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string MakeDisplay {
            get {
                return this.makeDisplayField;
            }
            set {
                this.makeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public string ModelDisplay {
            get {
                return this.modelDisplayField;
            }
            set {
                this.modelDisplayField = value;
            }
        }
        
        /// <remarks/>
        public string TrimDisplay {
            get {
                return this.trimDisplayField;
            }
            set {
                this.trimDisplayField = value;
            }
        }
        
        /// <remarks/>
        public UsedCarOptions[] UsedCarOptions {
            get {
                return this.usedCarOptionsField;
            }
            set {
                this.usedCarOptionsField = value;
            }
        }
        
        /// <remarks/>
        public int MSRP {
            get {
                return this.mSRPField;
            }
            set {
                this.mSRPField = value;
            }
        }
        
        /// <remarks/>
        public int AverageRetailPrice {
            get {
                return this.averageRetailPriceField;
            }
            set {
                this.averageRetailPriceField = value;
            }
        }
        
        /// <remarks/>
        public int AverageTradeinPrice {
            get {
                return this.averageTradeinPriceField;
            }
            set {
                this.averageTradeinPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceMinMax {
        
        private int minField;
        
        private int maxField;
        
        private MinMaxType typeField;
        
        /// <remarks/>
        public int Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        public int Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MinMaxType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public enum MinMaxType {
        
        /// <remarks/>
        MSRP,
        
        /// <remarks/>
        AverageRetailPrice,
        
        /// <remarks/>
        AverageTradeInPrice,
        
        /// <remarks/>
        HighRetailPrice,
        
        /// <remarks/>
        LowRetailPrice,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceMinMaxCollection {
        
        private PriceMinMax[] valuesField;
        
        /// <remarks/>
        public PriceMinMax[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarResultSet {
        
        private bool hasErrorField;
        
        private ErrorProfile errorField;
        
        private PriceMinMaxCollection priceMinMaxField;
        
        private string[] styleIDsField;
        
        private System.Guid transactionIDField;
        
        private UsedCar[] usedCarsField;
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public PriceMinMaxCollection PriceMinMax {
            get {
                return this.priceMinMaxField;
            }
            set {
                this.priceMinMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StyleIDs")]
        public string[] StyleIDs {
            get {
                return this.styleIDsField;
            }
            set {
                this.styleIDsField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsedCars")]
        public UsedCar[] UsedCars {
            get {
                return this.usedCarsField;
            }
            set {
                this.usedCarsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class ErrorProfile {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class MileageAdjustment {
        
        private string actualMileageField;
        
        private int adjustmentAmountField;
        
        private string acceptableRangeField;
        
        /// <remarks/>
        public string ActualMileage {
            get {
                return this.actualMileageField;
            }
            set {
                this.actualMileageField = value;
            }
        }
        
        /// <remarks/>
        public int AdjustmentAmount {
            get {
                return this.adjustmentAmountField;
            }
            set {
                this.adjustmentAmountField = value;
            }
        }
        
        /// <remarks/>
        public string AcceptableRange {
            get {
                return this.acceptableRangeField;
            }
            set {
                this.acceptableRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class pricing {
        
        private int priceTypeIDField;
        
        private string priceTypeField;
        
        private string priceTypeDisplayField;
        
        private int priceField;
        
        private string priceTypeExplanationField;
        
        /// <remarks/>
        public int PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeExplanation {
            get {
                return this.priceTypeExplanationField;
            }
            set {
                this.priceTypeExplanationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class Option {
        
        private bool isPercentField;
        
        private int priceTypeIDField;
        
        private string priceTypeField;
        
        private string priceTypeDisplayField;
        
        private int priceField;
        
        private int optionIDField;
        
        private string optionNameField;
        
        private string optionDisplayField;
        
        /// <remarks/>
        public bool IsPercent {
            get {
                return this.isPercentField;
            }
            set {
                this.isPercentField = value;
            }
        }
        
        /// <remarks/>
        public int PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        public string OptionName {
            get {
                return this.optionNameField;
            }
            set {
                this.optionNameField = value;
            }
        }
        
        /// <remarks/>
        public string OptionDisplay {
            get {
                return this.optionDisplayField;
            }
            set {
                this.optionDisplayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceTypeTotal {
        
        private string priceTypeIDField;
        
        private string priceTypeDisplayField;
        
        private int totalValueField;
        
        private int totalOptionField;
        
        /// <remarks/>
        public string PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int TotalValue {
            get {
                return this.totalValueField;
            }
            set {
                this.totalValueField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOption {
            get {
                return this.totalOptionField;
            }
            set {
                this.totalOptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarValue {
        
        private bool hasErrorField;
        
        private System.Xml.XmlNode messageField;
        
        private PriceTypeTotal[] usedValueTotalField;
        
        private Option[] usedValueOptionsField;
        
        private pricing[] basePriceField;
        
        private MileageAdjustment usedValueMileageField;
        
        private string transactionIDField;
        
        private string makeDisplayField;
        
        private string modelDisplayField;
        
        private int yearField;
        
        private string trimDisplayField;
        
        private ErrorProfile errorField;
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public PriceTypeTotal[] UsedValueTotal {
            get {
                return this.usedValueTotalField;
            }
            set {
                this.usedValueTotalField = value;
            }
        }
        
        /// <remarks/>
        public Option[] UsedValueOptions {
            get {
                return this.usedValueOptionsField;
            }
            set {
                this.usedValueOptionsField = value;
            }
        }
        
        /// <remarks/>
        public pricing[] BasePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        public MileageAdjustment UsedValueMileage {
            get {
                return this.usedValueMileageField;
            }
            set {
                this.usedValueMileageField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string MakeDisplay {
            get {
                return this.makeDisplayField;
            }
            set {
                this.makeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public string ModelDisplay {
            get {
                return this.modelDisplayField;
            }
            set {
                this.modelDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string TrimDisplay {
            get {
                return this.trimDisplayField;
            }
            set {
                this.trimDisplayField = value;
            }
        }
        
        /// <remarks/>
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarValueOption {
        
        private string transactionIDField;
        
        private ErrorProfile errorField;
        
        private UsedCarValue computedValueField;
        
        private UsedCarOptions[] availableOptionsField;
        
        private bool hasErrorField;
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public UsedCarValue ComputedValue {
            get {
                return this.computedValueField;
            }
            set {
                this.computedValueField = value;
            }
        }
        
        /// <remarks/>
        public UsedCarOptions[] AvailableOptions {
            get {
                return this.availableOptionsField;
            }
            set {
                this.availableOptionsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarOptionsTypedCompletedEventHandler(object sender, GetUsedCarOptionsTypedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarOptionsTypedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarOptionsTypedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarOptionList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarOptionList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarValueTypedwithOptionsCompletedEventHandler(object sender, GetUsedCarValueTypedwithOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarValueTypedwithOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarValueTypedwithOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarValueOption Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarValueOption)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarValueTypedCompletedEventHandler(object sender, GetUsedCarValueTypedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarValueTypedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarValueTypedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarValue Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarValue)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarOptionsCompletedEventHandler(object sender, GetUsedCarOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarValueCompletedEventHandler(object sender, GetUsedCarValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarsCompletedEventHandler(object sender, GetUsedCarsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarResultSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarResultSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarsNoVINCompletedEventHandler(object sender, GetUsedCarsNoVINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarsNoVINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarsNoVINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarResultSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarResultSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591