//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EDriveAutosDevModel", "FK_Product_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CarfaxScheduler.Product), "Product1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CarfaxScheduler.Product), true)]

#endregion

namespace CarfaxScheduler
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EDriveAutosDevEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EDriveAutosDevEntities object using the connection string found in the 'EDriveAutosDevEntities' section of the application configuration file.
        /// </summary>
        public EDriveAutosDevEntities() : base("name=EDriveAutosDevEntities", "EDriveAutosDevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EDriveAutosDevEntities object.
        /// </summary>
        public EDriveAutosDevEntities(string connectionString) : base(connectionString, "EDriveAutosDevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EDriveAutosDevEntities object.
        /// </summary>
        public EDriveAutosDevEntities(EntityConnection connection) : base(connection, "EDriveAutosDevEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CARFAX_DEALER> CARFAX_DEALER
        {
            get
            {
                if ((_CARFAX_DEALER == null))
                {
                    _CARFAX_DEALER = base.CreateObjectSet<CARFAX_DEALER>("CARFAX_DEALER");
                }
                return _CARFAX_DEALER;
            }
        }
        private ObjectSet<CARFAX_DEALER> _CARFAX_DEALER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ED_CarfaxLogDetail> ED_CarfaxLogDetail
        {
            get
            {
                if ((_ED_CarfaxLogDetail == null))
                {
                    _ED_CarfaxLogDetail = base.CreateObjectSet<ED_CarfaxLogDetail>("ED_CarfaxLogDetail");
                }
                return _ED_CarfaxLogDetail;
            }
        }
        private ObjectSet<ED_CarfaxLogDetail> _ED_CarfaxLogDetail;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CARFAX_DEALER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCARFAX_DEALER(CARFAX_DEALER cARFAX_DEALER)
        {
            base.AddObject("CARFAX_DEALER", cARFAX_DEALER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ED_CarfaxLogDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToED_CarfaxLogDetail(ED_CarfaxLogDetail eD_CarfaxLogDetail)
        {
            base.AddObject("ED_CarfaxLogDetail", eD_CarfaxLogDetail);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<CarfaxVehicleListItem> CarfaxVehicleList()
        {
            return base.ExecuteFunction<CarfaxVehicleListItem>("CarfaxVehicleList");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<CarfaxDealerListItem> CarfaxDealerList()
        {
            return base.ExecuteFunction<CarfaxDealerListItem>("CarfaxDealerList");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="file">No Metadata Documentation available.</param>
        public int ProductCarfaxReport(global::System.String file)
        {
            ObjectParameter fileParameter;
            if (file != null)
            {
                fileParameter = new ObjectParameter("File", file);
            }
            else
            {
                fileParameter = new ObjectParameter("File", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("ProductCarfaxReport", fileParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EDriveAutosDevModel", Name="CARFAX_DEALER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CARFAX_DEALER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CARFAX_DEALER object.
        /// </summary>
        /// <param name="dEALERID">Initial value of the DEALERID property.</param>
        public static CARFAX_DEALER CreateCARFAX_DEALER(global::System.Int32 dEALERID)
        {
            CARFAX_DEALER cARFAX_DEALER = new CARFAX_DEALER();
            cARFAX_DEALER.DEALERID = dEALERID;
            return cARFAX_DEALER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DEALERID
        {
            get
            {
                return _DEALERID;
            }
            set
            {
                if (_DEALERID != value)
                {
                    OnDEALERIDChanging(value);
                    ReportPropertyChanging("DEALERID");
                    _DEALERID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DEALERID");
                    OnDEALERIDChanged();
                }
            }
        }
        private global::System.Int32 _DEALERID;
        partial void OnDEALERIDChanging(global::System.Int32 value);
        partial void OnDEALERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEALERNAME
        {
            get
            {
                return _DEALERNAME;
            }
            set
            {
                OnDEALERNAMEChanging(value);
                ReportPropertyChanging("DEALERNAME");
                _DEALERNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEALERNAME");
                OnDEALERNAMEChanged();
            }
        }
        private global::System.String _DEALERNAME;
        partial void OnDEALERNAMEChanging(global::System.String value);
        partial void OnDEALERNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS1
        {
            get
            {
                return _ADDRESS1;
            }
            set
            {
                OnADDRESS1Changing(value);
                ReportPropertyChanging("ADDRESS1");
                _ADDRESS1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS1");
                OnADDRESS1Changed();
            }
        }
        private global::System.String _ADDRESS1;
        partial void OnADDRESS1Changing(global::System.String value);
        partial void OnADDRESS1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS2
        {
            get
            {
                return _ADDRESS2;
            }
            set
            {
                OnADDRESS2Changing(value);
                ReportPropertyChanging("ADDRESS2");
                _ADDRESS2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS2");
                OnADDRESS2Changed();
            }
        }
        private global::System.String _ADDRESS2;
        partial void OnADDRESS2Changing(global::System.String value);
        partial void OnADDRESS2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CITY
        {
            get
            {
                return _CITY;
            }
            set
            {
                OnCITYChanging(value);
                ReportPropertyChanging("CITY");
                _CITY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CITY");
                OnCITYChanged();
            }
        }
        private global::System.String _CITY;
        partial void OnCITYChanging(global::System.String value);
        partial void OnCITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STATE
        {
            get
            {
                return _STATE;
            }
            set
            {
                OnSTATEChanging(value);
                ReportPropertyChanging("STATE");
                _STATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STATE");
                OnSTATEChanged();
            }
        }
        private global::System.String _STATE;
        partial void OnSTATEChanging(global::System.String value);
        partial void OnSTATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIP
        {
            get
            {
                return _ZIP;
            }
            set
            {
                OnZIPChanging(value);
                ReportPropertyChanging("ZIP");
                _ZIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIP");
                OnZIPChanged();
            }
        }
        private global::System.String _ZIP;
        partial void OnZIPChanging(global::System.String value);
        partial void OnZIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TELEPHONE
        {
            get
            {
                return _TELEPHONE;
            }
            set
            {
                OnTELEPHONEChanging(value);
                ReportPropertyChanging("TELEPHONE");
                _TELEPHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TELEPHONE");
                OnTELEPHONEChanged();
            }
        }
        private global::System.String _TELEPHONE;
        partial void OnTELEPHONEChanging(global::System.String value);
        partial void OnTELEPHONEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EDriveAutosDevModel", Name="ED_CarfaxLogDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ED_CarfaxLogDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ED_CarfaxLogDetail object.
        /// </summary>
        /// <param name="carFax_logID">Initial value of the CarFax_logID property.</param>
        /// <param name="logMsg">Initial value of the LogMsg property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="createBy">Initial value of the CreateBy property.</param>
        /// <param name="createOn">Initial value of the CreateOn property.</param>
        public static ED_CarfaxLogDetail CreateED_CarfaxLogDetail(global::System.Int32 carFax_logID, global::System.String logMsg, global::System.Int32 status, global::System.Int32 createBy, global::System.DateTime createOn)
        {
            ED_CarfaxLogDetail eD_CarfaxLogDetail = new ED_CarfaxLogDetail();
            eD_CarfaxLogDetail.CarFax_logID = carFax_logID;
            eD_CarfaxLogDetail.LogMsg = logMsg;
            eD_CarfaxLogDetail.Status = status;
            eD_CarfaxLogDetail.CreateBy = createBy;
            eD_CarfaxLogDetail.CreateOn = createOn;
            return eD_CarfaxLogDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CarFax_logID
        {
            get
            {
                return _CarFax_logID;
            }
            set
            {
                if (_CarFax_logID != value)
                {
                    OnCarFax_logIDChanging(value);
                    ReportPropertyChanging("CarFax_logID");
                    _CarFax_logID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CarFax_logID");
                    OnCarFax_logIDChanged();
                }
            }
        }
        private global::System.Int32 _CarFax_logID;
        partial void OnCarFax_logIDChanging(global::System.Int32 value);
        partial void OnCarFax_logIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LogMsg
        {
            get
            {
                return _LogMsg;
            }
            set
            {
                OnLogMsgChanging(value);
                ReportPropertyChanging("LogMsg");
                _LogMsg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LogMsg");
                OnLogMsgChanged();
            }
        }
        private global::System.String _LogMsg;
        partial void OnLogMsgChanging(global::System.String value);
        partial void OnLogMsgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Success
        {
            get
            {
                return _Success;
            }
            set
            {
                OnSuccessChanging(value);
                ReportPropertyChanging("Success");
                _Success = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Success");
                OnSuccessChanged();
            }
        }
        private Nullable<global::System.Int32> _Success;
        partial void OnSuccessChanging(Nullable<global::System.Int32> value);
        partial void OnSuccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreateBy
        {
            get
            {
                return _CreateBy;
            }
            set
            {
                OnCreateByChanging(value);
                ReportPropertyChanging("CreateBy");
                _CreateBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateBy");
                OnCreateByChanged();
            }
        }
        private global::System.Int32 _CreateBy;
        partial void OnCreateByChanging(global::System.Int32 value);
        partial void OnCreateByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateOn
        {
            get
            {
                return _CreateOn;
            }
            set
            {
                OnCreateOnChanging(value);
                ReportPropertyChanging("CreateOn");
                _CreateOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateOn");
                OnCreateOnChanged();
            }
        }
        private global::System.DateTime _CreateOn;
        partial void OnCreateOnChanging(global::System.DateTime value);
        partial void OnCreateOnChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EDriveAutosDevModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        /// <param name="createdOn">Initial value of the CreatedOn property.</param>
        /// <param name="updatedOn">Initial value of the UpdatedOn property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="iSQUALIFIED">Initial value of the ISQUALIFIED property.</param>
        public static Product CreateProduct(global::System.Int32 productId, global::System.String name, global::System.Boolean deleted, global::System.DateTime createdOn, global::System.DateTime updatedOn, global::System.Int32 type, global::System.Int32 model, global::System.Int32 body, global::System.Boolean iSQUALIFIED)
        {
            Product product = new Product();
            product.ProductId = productId;
            product.Name = name;
            product.Deleted = deleted;
            product.CreatedOn = createdOn;
            product.UpdatedOn = updatedOn;
            product.Type = type;
            product.Model = model;
            product.Body = body;
            product.ISQUALIFIED = iSQUALIFIED;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                if (_ProductId != value)
                {
                    OnProductIdChanging(value);
                    ReportPropertyChanging("ProductId");
                    _ProductId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductId");
                    OnProductIdChanged();
                }
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedOn
        {
            get
            {
                return _UpdatedOn;
            }
            set
            {
                OnUpdatedOnChanging(value);
                ReportPropertyChanging("UpdatedOn");
                _UpdatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedOn");
                OnUpdatedOnChanged();
            }
        }
        private global::System.DateTime _UpdatedOn;
        partial void OnUpdatedOnChanging(global::System.DateTime value);
        partial void OnUpdatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VIN
        {
            get
            {
                return _VIN;
            }
            set
            {
                OnVINChanging(value);
                ReportPropertyChanging("VIN");
                _VIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VIN");
                OnVINChanged();
            }
        }
        private global::System.String _VIN;
        partial void OnVINChanging(global::System.String value);
        partial void OnVINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CustomerID;
        partial void OnCustomerIDChanging(Nullable<global::System.Int32> value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private global::System.String _Stock;
        partial void OnStockChanging(global::System.String value);
        partial void OnStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private Nullable<global::System.Int32> _Year;
        partial void OnYearChanging(Nullable<global::System.Int32> value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.Int32 _Model;
        partial void OnModelChanging(global::System.Int32 value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trim
        {
            get
            {
                return _Trim;
            }
            set
            {
                OnTrimChanging(value);
                ReportPropertyChanging("Trim");
                _Trim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trim");
                OnTrimChanged();
            }
        }
        private global::System.String _Trim;
        partial void OnTrimChanging(global::System.String value);
        partial void OnTrimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Free_Text
        {
            get
            {
                return _Free_Text;
            }
            set
            {
                OnFree_TextChanging(value);
                ReportPropertyChanging("Free_Text");
                _Free_Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Free_Text");
                OnFree_TextChanged();
            }
        }
        private global::System.String _Free_Text;
        partial void OnFree_TextChanging(global::System.String value);
        partial void OnFree_TextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.Int32 _Body;
        partial void OnBodyChanging(global::System.Int32 value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Mileage
        {
            get
            {
                return _Mileage;
            }
            set
            {
                OnMileageChanging(value);
                ReportPropertyChanging("Mileage");
                _Mileage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mileage");
                OnMileageChanged();
            }
        }
        private Nullable<global::System.Int32> _Mileage;
        partial void OnMileageChanging(Nullable<global::System.Int32> value);
        partial void OnMileageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price_Current
        {
            get
            {
                return _Price_Current;
            }
            set
            {
                OnPrice_CurrentChanging(value);
                ReportPropertyChanging("Price_Current");
                _Price_Current = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price_Current");
                OnPrice_CurrentChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price_Current;
        partial void OnPrice_CurrentChanging(Nullable<global::System.Decimal> value);
        partial void OnPrice_CurrentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Condition
        {
            get
            {
                return _Condition;
            }
            set
            {
                OnConditionChanging(value);
                ReportPropertyChanging("Condition");
                _Condition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Condition");
                OnConditionChanged();
            }
        }
        private global::System.String _Condition;
        partial void OnConditionChanging(global::System.String value);
        partial void OnConditionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exterior_Color
        {
            get
            {
                return _Exterior_Color;
            }
            set
            {
                OnExterior_ColorChanging(value);
                ReportPropertyChanging("Exterior_Color");
                _Exterior_Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exterior_Color");
                OnExterior_ColorChanged();
            }
        }
        private global::System.String _Exterior_Color;
        partial void OnExterior_ColorChanging(global::System.String value);
        partial void OnExterior_ColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Interior_Color
        {
            get
            {
                return _Interior_Color;
            }
            set
            {
                OnInterior_ColorChanging(value);
                ReportPropertyChanging("Interior_Color");
                _Interior_Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Interior_Color");
                OnInterior_ColorChanged();
            }
        }
        private global::System.String _Interior_Color;
        partial void OnInterior_ColorChanging(global::System.String value);
        partial void OnInterior_ColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Doors
        {
            get
            {
                return _Doors;
            }
            set
            {
                OnDoorsChanging(value);
                ReportPropertyChanging("Doors");
                _Doors = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Doors");
                OnDoorsChanged();
            }
        }
        private Nullable<global::System.Int32> _Doors;
        partial void OnDoorsChanging(Nullable<global::System.Int32> value);
        partial void OnDoorsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Engine
        {
            get
            {
                return _Engine;
            }
            set
            {
                OnEngineChanging(value);
                ReportPropertyChanging("Engine");
                _Engine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Engine");
                OnEngineChanged();
            }
        }
        private global::System.String _Engine;
        partial void OnEngineChanging(global::System.String value);
        partial void OnEngineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transmission
        {
            get
            {
                return _Transmission;
            }
            set
            {
                OnTransmissionChanging(value);
                ReportPropertyChanging("Transmission");
                _Transmission = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transmission");
                OnTransmissionChanged();
            }
        }
        private global::System.String _Transmission;
        partial void OnTransmissionChanging(global::System.String value);
        partial void OnTransmissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fuel_Type
        {
            get
            {
                return _Fuel_Type;
            }
            set
            {
                OnFuel_TypeChanging(value);
                ReportPropertyChanging("Fuel_Type");
                _Fuel_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fuel_Type");
                OnFuel_TypeChanged();
            }
        }
        private global::System.String _Fuel_Type;
        partial void OnFuel_TypeChanging(global::System.String value);
        partial void OnFuel_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Drive_Type
        {
            get
            {
                return _Drive_Type;
            }
            set
            {
                OnDrive_TypeChanging(value);
                ReportPropertyChanging("Drive_Type");
                _Drive_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Drive_Type");
                OnDrive_TypeChanged();
            }
        }
        private global::System.String _Drive_Type;
        partial void OnDrive_TypeChanging(global::System.String value);
        partial void OnDrive_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Warranty
        {
            get
            {
                return _Warranty;
            }
            set
            {
                OnWarrantyChanging(value);
                ReportPropertyChanging("Warranty");
                _Warranty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warranty");
                OnWarrantyChanged();
            }
        }
        private Nullable<global::System.Boolean> _Warranty;
        partial void OnWarrantyChanging(Nullable<global::System.Boolean> value);
        partial void OnWarrantyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_in_Stock
        {
            get
            {
                return _Date_in_Stock;
            }
            set
            {
                OnDate_in_StockChanging(value);
                ReportPropertyChanging("Date_in_Stock");
                _Date_in_Stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_in_Stock");
                OnDate_in_StockChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_in_Stock;
        partial void OnDate_in_StockChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_in_StockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsNew
        {
            get
            {
                return _IsNew;
            }
            set
            {
                OnIsNewChanging(value);
                ReportPropertyChanging("IsNew");
                _IsNew = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNew");
                OnIsNewChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsNew;
        partial void OnIsNewChanging(Nullable<global::System.Boolean> value);
        partial void OnIsNewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsFeature
        {
            get
            {
                return _IsFeature;
            }
            set
            {
                OnIsFeatureChanging(value);
                ReportPropertyChanging("IsFeature");
                _IsFeature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFeature");
                OnIsFeatureChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsFeature;
        partial void OnIsFeatureChanging(Nullable<global::System.Boolean> value);
        partial void OnIsFeatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SavingAmount
        {
            get
            {
                return _SavingAmount;
            }
            set
            {
                OnSavingAmountChanging(value);
                ReportPropertyChanging("SavingAmount");
                _SavingAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SavingAmount");
                OnSavingAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _SavingAmount;
        partial void OnSavingAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnSavingAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StateID
        {
            get
            {
                return _StateID;
            }
            set
            {
                OnStateIDChanging(value);
                ReportPropertyChanging("StateID");
                _StateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateID");
                OnStateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StateID;
        partial void OnStateIDChanging(Nullable<global::System.Int32> value);
        partial void OnStateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> QualifyPrice
        {
            get
            {
                return _QualifyPrice;
            }
            set
            {
                OnQualifyPriceChanging(value);
                ReportPropertyChanging("QualifyPrice");
                _QualifyPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QualifyPrice");
                OnQualifyPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _QualifyPrice;
        partial void OnQualifyPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnQualifyPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AverageRetailPrice
        {
            get
            {
                return _AverageRetailPrice;
            }
            set
            {
                OnAverageRetailPriceChanging(value);
                ReportPropertyChanging("AverageRetailPrice");
                _AverageRetailPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AverageRetailPrice");
                OnAverageRetailPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _AverageRetailPrice;
        partial void OnAverageRetailPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnAverageRetailPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AverageTradeinPrice
        {
            get
            {
                return _AverageTradeinPrice;
            }
            set
            {
                OnAverageTradeinPriceChanging(value);
                ReportPropertyChanging("AverageTradeinPrice");
                _AverageTradeinPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AverageTradeinPrice");
                OnAverageTradeinPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _AverageTradeinPrice;
        partial void OnAverageTradeinPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnAverageTradeinPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> City_Fuel
        {
            get
            {
                return _City_Fuel;
            }
            set
            {
                OnCity_FuelChanging(value);
                ReportPropertyChanging("City_Fuel");
                _City_Fuel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("City_Fuel");
                OnCity_FuelChanged();
            }
        }
        private Nullable<global::System.Int32> _City_Fuel;
        partial void OnCity_FuelChanging(Nullable<global::System.Int32> value);
        partial void OnCity_FuelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Highway_Fuel
        {
            get
            {
                return _Highway_Fuel;
            }
            set
            {
                OnHighway_FuelChanging(value);
                ReportPropertyChanging("Highway_Fuel");
                _Highway_Fuel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Highway_Fuel");
                OnHighway_FuelChanged();
            }
        }
        private Nullable<global::System.Int32> _Highway_Fuel;
        partial void OnHighway_FuelChanging(Nullable<global::System.Int32> value);
        partial void OnHighway_FuelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private Nullable<global::System.Int32> _zip;
        partial void OnzipChanging(Nullable<global::System.Int32> value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reserved
        {
            get
            {
                return _Reserved;
            }
            set
            {
                OnReservedChanging(value);
                ReportPropertyChanging("Reserved");
                _Reserved = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reserved");
                OnReservedChanged();
            }
        }
        private global::System.String _Reserved;
        partial void OnReservedChanging(global::System.String value);
        partial void OnReservedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price_Cost
        {
            get
            {
                return _Price_Cost;
            }
            set
            {
                OnPrice_CostChanging(value);
                ReportPropertyChanging("Price_Cost");
                _Price_Cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price_Cost");
                OnPrice_CostChanged();
            }
        }
        private Nullable<global::System.Double> _Price_Cost;
        partial void OnPrice_CostChanging(Nullable<global::System.Double> value);
        partial void OnPrice_CostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price_WholeSale
        {
            get
            {
                return _Price_WholeSale;
            }
            set
            {
                OnPrice_WholeSaleChanging(value);
                ReportPropertyChanging("Price_WholeSale");
                _Price_WholeSale = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price_WholeSale");
                OnPrice_WholeSaleChanged();
            }
        }
        private Nullable<global::System.Double> _Price_WholeSale;
        partial void OnPrice_WholeSaleChanging(Nullable<global::System.Double> value);
        partial void OnPrice_WholeSaleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pics
        {
            get
            {
                return _Pics;
            }
            set
            {
                OnPicsChanging(value);
                ReportPropertyChanging("Pics");
                _Pics = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pics");
                OnPicsChanged();
            }
        }
        private global::System.String _Pics;
        partial void OnPicsChanging(global::System.String value);
        partial void OnPicsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OwnerDetail
        {
            get
            {
                return _OwnerDetail;
            }
            set
            {
                OnOwnerDetailChanging(value);
                ReportPropertyChanging("OwnerDetail");
                _OwnerDetail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OwnerDetail");
                OnOwnerDetailChanged();
            }
        }
        private global::System.String _OwnerDetail;
        partial void OnOwnerDetailChanging(global::System.String value);
        partial void OnOwnerDetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ShowOnDealerProfile
        {
            get
            {
                return _ShowOnDealerProfile;
            }
            set
            {
                OnShowOnDealerProfileChanging(value);
                ReportPropertyChanging("ShowOnDealerProfile");
                _ShowOnDealerProfile = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowOnDealerProfile");
                OnShowOnDealerProfileChanged();
            }
        }
        private Nullable<global::System.Boolean> _ShowOnDealerProfile;
        partial void OnShowOnDealerProfileChanging(Nullable<global::System.Boolean> value);
        partial void OnShowOnDealerProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SellerEmail
        {
            get
            {
                return _SellerEmail;
            }
            set
            {
                OnSellerEmailChanging(value);
                ReportPropertyChanging("SellerEmail");
                _SellerEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SellerEmail");
                OnSellerEmailChanged();
            }
        }
        private global::System.String _SellerEmail;
        partial void OnSellerEmailChanging(global::System.String value);
        partial void OnSellerEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SellerName
        {
            get
            {
                return _SellerName;
            }
            set
            {
                OnSellerNameChanging(value);
                ReportPropertyChanging("SellerName");
                _SellerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SellerName");
                OnSellerNameChanged();
            }
        }
        private global::System.String _SellerName;
        partial void OnSellerNameChanging(global::System.String value);
        partial void OnSellerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Offer
        {
            get
            {
                return _Offer;
            }
            set
            {
                OnOfferChanging(value);
                ReportPropertyChanging("Offer");
                _Offer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Offer");
                OnOfferChanged();
            }
        }
        private Nullable<global::System.Boolean> _Offer;
        partial void OnOfferChanging(Nullable<global::System.Boolean> value);
        partial void OnOfferChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ISQUALIFIED
        {
            get
            {
                return _ISQUALIFIED;
            }
            set
            {
                OnISQUALIFIEDChanging(value);
                ReportPropertyChanging("ISQUALIFIED");
                _ISQUALIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISQUALIFIED");
                OnISQUALIFIEDChanged();
            }
        }
        private global::System.Boolean _ISQUALIFIED;
        partial void OnISQUALIFIEDChanging(global::System.Boolean value);
        partial void OnISQUALIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NADACheckedOn
        {
            get
            {
                return _NADACheckedOn;
            }
            set
            {
                OnNADACheckedOnChanging(value);
                ReportPropertyChanging("NADACheckedOn");
                _NADACheckedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NADACheckedOn");
                OnNADACheckedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _NADACheckedOn;
        partial void OnNADACheckedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnNADACheckedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EDriveAutosDevModel", "FK_Product_Product", "Product1")]
        public Product Product1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> Product1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EDriveAutosDevModel", "FK_Product_Product", "Product")]
        public Product Product2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> Product2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("EDriveAutosDevModel.FK_Product_Product", "Product", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EDriveAutosDevModel", Name="CarfaxDealerListItem")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CarfaxDealerListItem : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Column1
        {
            get
            {
                return _Column1;
            }
            set
            {
                OnColumn1Changing(value);
                ReportPropertyChanging("Column1");
                _Column1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Column1");
                OnColumn1Changed();
            }
        }
        private global::System.String _Column1;
        partial void OnColumn1Changing(global::System.String value);
        partial void OnColumn1Changed();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EDriveAutosDevModel", Name="CarfaxVehicleListItem")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CarfaxVehicleListItem : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Column1
        {
            get
            {
                return _Column1;
            }
            set
            {
                OnColumn1Changing(value);
                ReportPropertyChanging("Column1");
                _Column1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Column1");
                OnColumn1Changed();
            }
        }
        private global::System.String _Column1;
        partial void OnColumn1Changing(global::System.String value);
        partial void OnColumn1Changed();

        #endregion
    }

    #endregion
    
}
