CREATE UNIQUE NONCLUSTERED INDEX [Ed_ZipCodes_latitude]
    ON [dbo].[ED_Zipcodes]([latitude] ASC, [longitude] ASC, [ZipID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

