CREATE PROCEDURE [dbo].[Nop_ProductInsert]
(
	@ProductID int = NULL output,
	@Name nvarchar(400),
	@ShortDescription nvarchar(MAX),
	@FullDescription nvarchar(MAX),
	@AdminComment nvarchar(MAX),
	@ProductTypeID int,
	@TemplateID int,
	@ShowOnHomePage bit,
	@MetaKeywords nvarchar(400),
	@MetaDescription nvarchar(4000),
	@MetaTitle nvarchar(400),
	@SEName nvarchar(100),
	@AllowCustomerReviews bit,
	@AllowCustomerRatings bit,
	@RatingSum int,
	@TotalRatingVotes int,
	@Published bit,
	@Deleted bit,
	@CreatedOn datetime,
	@UpdatedOn datetime,
	@VIN nvarchar(50),
	@CustomerID int,
	@VehicleName nvarchar(250),
	@Type nvarchar(50),
	@TypeAttribute int,
	@Stock nvarchar(50),
	@Year nvarchar(50),
	@YearAttribute int,
	@Make nvarchar(50),
	@MakeAttribute int,
	@Model nvarchar(50),
	@Trim nvarchar(50),
	@Free_Text nvarchar(MAX),
	@Body nvarchar(50),
	@BodyAttribute int,
	@Mileage nvarchar(50),
	@MileageAttribute int,
	@Price_Current money,
	@Reserved nvarchar(50),
	@Price_Wholesale money,
	@Price_Cost money,
	@PriceAttribute int,
	@Title nvarchar(50),
	@Condition nvarchar(50),
	@Exterior_Color nvarchar(50),
	@Interior_Color nvarchar(50),
	@Doors nvarchar(20),
	@Engine nvarchar(50),
	@Transmission nvarchar(50),
	@Fuel_Type nvarchar(50),
	@Drive_Type nvarchar(50),
	@Options nvarchar(MAX),
	@Warranty nvarchar(50),
	@WarrantyAttribute int,
	@Description nvarchar(MAX),
	@Pics nvarchar(MAX),
	@Dealer_Name nvarchar(MAX),
	@Dealer_Zip nvarchar(MAX),
	@SavingAmount money,
	@City nvarchar(MAX),
	@StateID int,
	@Date_in_Stock datetime,
	@FileName nvarchar(MAX),
	@IsNew bit,
	@IsFeature bit,
	@QualifyPrice money,
	@OwnerDetail varchar(500),
	@Show_on_Dealer bit,
	@Offer bit,
	@City_Fuel int,
	@Highway_Fuel int,
	@AverageRetailPrice money,
	@AverageTradeinPrice money,
	@SellerName nvarchar(150),
	@SellerEmail nvarchar(150),
	@SellerPhone nvarchar(150),
	@SellerNotes nvarchar(MAX)
)
AS
BEGIN
	INSERT
	INTO [Nop_Product]
	(
		[Name],
		ShortDescription,
		FullDescription,
		AdminComment,
		ProductTypeID,
		TemplateID,
		ShowOnHomePage,
		MetaKeywords,
		MetaDescription,
		MetaTitle,
		SEName,
		AllowCustomerReviews,
		AllowCustomerRatings,
		RatingSum,
		TotalRatingVotes,
		Published,
		Deleted,
		CreatedOn,
		UpdatedOn,
		VIN,
		CustomerID,
		VehicleName,
		[Type],
		TypeAttribute,
		Stock,
		[Year],
		YearAttribute,
		Make,
		MakeAttribute,
		Model,
		Trim,
		Free_Text,
		Body,
		BodyAttribute,
		Mileage,
		MileageAttribute,
		Price_Current,
		Reserved,
		Price_Wholesale,
		Price_Cost,
		PriceAttribute,
		Title,
		Condition,
		Exterior_Color,
		Interior_Color,
		Doors,
		Engine,
		Transmission,
		Fuel_Type,
		Drive_Type,
		Options,
		Warranty,
		WarrantyAttribute,
		Description,
		Pics,
		Dealer_Name,
		Dealer_Zip,
		SavingAmount,
		City,
		StateID,
		Date_in_Stock,
		[FileName],
		IsNew,
		IsFeature,
		QualifyPrice,
		OwnerDetail,
		Show_on_Dealer,
		Offer,
		City_Fuel,
	    Highway_Fuel,
	    AverageRetailPrice ,
	    AverageTradeinPrice,
	    SellerName ,
	    SellerEmail,
	    SellerPhone,
	    SellerNotes
	)
	VALUES
	(
		@Name,
		@ShortDescription,
		@FullDescription,
		@AdminComment,
		@ProductTypeID,
		@TemplateID,
		@ShowOnHomePage,
		@MetaKeywords,
		@MetaDescription,
		@MetaTitle,
		@SEName,
		@AllowCustomerReviews,
		@AllowCustomerRatings,
		@RatingSum,
		@TotalRatingVotes,
		@Published,
		@Deleted,
		@CreatedOn,
		@UpdatedOn,
		@VIN,
		@CustomerID,
		@VehicleName,
		@Type,
		@TypeAttribute,
		@Stock,
		@Year,
		@YearAttribute,
		@Make,
		@MakeAttribute,
		@Model,
		@Trim,
		@Free_Text,
		@Body,
		@BodyAttribute,
		@Mileage,
		@MileageAttribute,
		@Price_Current,
		@Reserved,
		@Price_Wholesale,
		@Price_Cost,
		@PriceAttribute,
		@Title,
		@Condition,
		@Exterior_Color,
		@Interior_Color,
		@Doors,
		@Engine,
		@Transmission,
		@Fuel_Type,
		@Drive_Type,
		@Options,
		@Warranty,
		@WarrantyAttribute,
		@Description,
		@Pics,
		@Dealer_Name,
		@Dealer_Zip,
		@SavingAmount,
		@City,
		@StateID,
		@Date_in_Stock,
		@FileName,
		@IsNew,
		@IsFeature,
		@QualifyPrice,
		@OwnerDetail,
		@Show_on_Dealer,
		@Offer,
		@City_Fuel,
		@Highway_Fuel,
		@AverageRetailPrice,
		@AverageTradeinPrice,
		@SellerName ,
		@SellerEmail ,
		@SellerPhone,
		@SellerNotes
	)

	set @ProductID=SCOPE_IDENTITY()
END