CREATE PROCEDURE [dbo].[Nop_ProductUpdate]
(
	@ProductID int,
	@Name nvarchar(400),
	@ShortDescription nvarchar(MAX),
	@FullDescription nvarchar(MAX),
	@AdminComment nvarchar(MAX),
	@ProductTypeID int,
	@TemplateID int,
	@ShowOnHomePage bit,
	@MetaKeywords nvarchar(400),
	@MetaDescription nvarchar(4000),
	@MetaTitle nvarchar(400),
	@SEName nvarchar(100),
	@AllowCustomerReviews bit,
	@AllowCustomerRatings bit,
	@RatingSum int,
	@TotalRatingVotes int,
	@Published bit,
	@Deleted bit,
	@CreatedOn datetime,
	@UpdatedOn datetime,
	@VIN nvarchar(50),
	@CustomerID int,
	@VehicleName nvarchar(250),
	@Type nvarchar(50),
	@TypeAttribute int,
	@Stock nvarchar(50),
	@Year nvarchar(50),
	@YearAttribute int,
	@Make nvarchar(50),
	@MakeAttribute int,
	@Model nvarchar(50),
	@Trim nvarchar(50),
	@Free_Text nvarchar(MAX),
	@Body nvarchar(50),
	@BodyAttribute int,
	@Mileage nvarchar(50),
	@MileageAttribute int,
	@Price_Current money,
	@Reserved nvarchar(50),
	@Price_Wholesale money,
	@Price_Cost money,
	@PriceAttribute int,
	@Title nvarchar(50),
	@Condition nvarchar(50),
	@Exterior_Color nvarchar(50),
	@Interior_Color nvarchar(50),
	@Doors nvarchar(20),
	@Engine nvarchar(50),
	@Transmission nvarchar(50),
	@Fuel_Type nvarchar(50),
	@Drive_Type nvarchar(50),
	@Options nvarchar(MAX),
	@Warranty nvarchar(50),
	@WarrantyAttribute int,
	@Description nvarchar(MAX),
	@Pics nvarchar(MAX),
	@Dealer_Name nvarchar(MAX) ,
	@Dealer_Zip nvarchar(MAX),
	@Date_in_Stock datetime,
	@SavingAmount money,
	@City nvarchar(MAX),
	@StateID int,
	@FileName nvarchar(MAX),
	@IsNew bit,
	@IsFeature bit,
	@QualifyPrice money,
	@OwnerDetail varchar(500),
	@Show_on_Dealer bit,
	@Offer bit,
	@City_Fuel int,
	@Highway_Fuel int,
	@AverageRetailPrice money,
	@AverageTradeinPrice money,
	@SellerName nvarchar(150),
	@SellerEmail nvarchar(150),
	@SellerPhone nvarchar(150),
	@SellerNotes nvarchar(150)
)
AS
BEGIN
	UPDATE [Nop_Product]
	SET
		[Name]=@Name,
		ShortDescription=@ShortDescription,
		FullDescription=@FullDescription,
		AdminComment=@AdminComment,
		ProductTypeID=@ProductTypeID,
		TemplateID=@TemplateID,
		ShowOnHomePage=@ShowOnHomePage,
		MetaKeywords=@MetaKeywords,
		MetaDescription=@MetaDescription,
		MetaTitle=@MetaTitle,
		SEName=@SEName,
		AllowCustomerReviews=@AllowCustomerReviews,
		AllowCustomerRatings=@AllowCustomerRatings,
		RatingSum=@RatingSum,
		TotalRatingVotes=@TotalRatingVotes,
		Published=@Published,
		Deleted=@Deleted,
		CreatedOn=@CreatedOn,
		UpdatedOn=@UpdatedOn,
		VIN=@VIN,
		CustomerID=@CustomerID,
		VehicleName=@VehicleName,
		[Type]=@Type,
		TypeAttribute=@TypeAttribute,
		Stock=@Stock,
		[Year]=@Year,
		YearAttribute=@YearAttribute,
		Make=@Make,
		MakeAttribute=@MakeAttribute,
		Model=@Model,
		Trim=@Trim,
		Free_Text=@Free_Text,
		Body=@Body,
		BodyAttribute=@BodyAttribute,
		Mileage=@Mileage,
		MileageAttribute=@MileageAttribute,
		Price_Current=@Price_Current,
		Reserved=@Reserved,
		Price_Wholesale=@Price_Wholesale,
		Price_Cost=@Price_Cost,
		PriceAttribute=@PriceAttribute,
		Title=@Title,
		Condition=@Condition,
		Exterior_Color=@Exterior_Color,
		Interior_Color=@Interior_Color,
		Doors=@Doors,
		Engine=@Engine,
		Transmission=@Transmission,
		Fuel_Type=@Fuel_Type,
		Drive_Type=@Drive_Type,
		Options=@Options,
		Warranty=@Warranty,
		WarrantyAttribute=@WarrantyAttribute,
		Description=@Description,
		Pics=@Pics,
		Dealer_Name=@Dealer_Name,
		Dealer_Zip=@Dealer_Zip,
		SavingAmount=@SavingAmount,
		City=@City,
		StateID=@StateID,
		Date_in_Stock=@Date_in_Stock,
		[FileName]=@FileName,
		IsNew=@IsNew,
		IsFeature=@IsFeature,
		QualifyPrice =@QualifyPrice ,
		OwnerDetail=@OwnerDetail,
		Show_on_Dealer=@Show_on_Dealer,
		Offer =@Offer,
		City_Fuel= @City_Fuel,
		Highway_Fuel = @Highway_Fuel ,
		AverageRetailPrice =@AverageRetailPrice ,
		AverageTradeinPrice =@AverageTradeinPrice ,
		SellerName =@SellerName ,
		SellerEmail=@SellerEmail ,
		SellerPhone =@SellerPhone ,
		SellerNotes =@SellerNotes 
	WHERE
		[ProductID] = @ProductID
END