//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.517
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadaScheduler.NadaUsedCars {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UsedCar.NADAguides.com", ConfigurationName="NadaUsedCars.UsedCarsSoap")]
    public interface UsedCarsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCarOptionsTyped", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NadaScheduler.NadaUsedCars.UsedCarOptionList GetUsedCarOptionsTyped(string UserID, string Password, string StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCarValueTypedwithOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NadaScheduler.NadaUsedCars.UsedCarValueOption GetUsedCarValueTypedwithOptions(string UserID, string Password, string StyleID, string options, string mileage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCarValueTyped", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NadaScheduler.NadaUsedCars.UsedCarValue GetUsedCarValueTyped(string UserID, string Password, string StyleID, string options, string mileage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCarOptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetUsedCarOptions(string UserID, string Password, string StyleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCarValue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetUsedCarValue(string UserID, string Password, string StyleID, string Options, string Mileage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCars", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NadaScheduler.NadaUsedCars.UsedCarResultSet GetUsedCars(string UserName, string Password, string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UsedCar.NADAguides.com/GetUsedCarsNoVIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NadaScheduler.NadaUsedCars.UsedCarResultSet GetUsedCarsNoVIN(string UserName, string Password, string NewCarStyleIDs);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarOptionList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode messageField;
        
        private UsedCarOptions[] optionListField;
        
        private string transactionIDField;
        
        private bool hasErrorField;
        
        private ErrorProfile errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Xml.XmlNode Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public UsedCarOptions[] OptionList {
            get {
                return this.optionListField;
            }
            set {
                this.optionListField = value;
                this.RaisePropertyChanged("OptionList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
                this.RaisePropertyChanged("HasError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarOptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int optionIDField;
        
        private string displayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
                this.RaisePropertyChanged("OptionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int highRetailField;
        
        private int lowRetailField;
        
        private int cityFuelLowField;
        
        private int cityFuelHighField;
        
        private int highwayFuelLowField;
        
        private int highwayFuelHighField;
        
        private int styleIDField;
        
        private int makeIDField;
        
        private int optionKeyIDField;
        
        private int modelIDField;
        
        private int c_ModelIDField;
        
        private int yearField;
        
        private string makeDisplayField;
        
        private string modelDisplayField;
        
        private string trimDisplayField;
        
        private UsedCarOptions[] usedCarOptionsField;
        
        private int mSRPField;
        
        private int averageRetailPriceField;
        
        private int averageTradeinPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HighRetail {
            get {
                return this.highRetailField;
            }
            set {
                this.highRetailField = value;
                this.RaisePropertyChanged("HighRetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LowRetail {
            get {
                return this.lowRetailField;
            }
            set {
                this.lowRetailField = value;
                this.RaisePropertyChanged("LowRetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CityFuelLow {
            get {
                return this.cityFuelLowField;
            }
            set {
                this.cityFuelLowField = value;
                this.RaisePropertyChanged("CityFuelLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CityFuelHigh {
            get {
                return this.cityFuelHighField;
            }
            set {
                this.cityFuelHighField = value;
                this.RaisePropertyChanged("CityFuelHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int HighwayFuelLow {
            get {
                return this.highwayFuelLowField;
            }
            set {
                this.highwayFuelLowField = value;
                this.RaisePropertyChanged("HighwayFuelLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int HighwayFuelHigh {
            get {
                return this.highwayFuelHighField;
            }
            set {
                this.highwayFuelHighField = value;
                this.RaisePropertyChanged("HighwayFuelHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int StyleID {
            get {
                return this.styleIDField;
            }
            set {
                this.styleIDField = value;
                this.RaisePropertyChanged("StyleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int MakeID {
            get {
                return this.makeIDField;
            }
            set {
                this.makeIDField = value;
                this.RaisePropertyChanged("MakeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int OptionKeyID {
            get {
                return this.optionKeyIDField;
            }
            set {
                this.optionKeyIDField = value;
                this.RaisePropertyChanged("OptionKeyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ModelID {
            get {
                return this.modelIDField;
            }
            set {
                this.modelIDField = value;
                this.RaisePropertyChanged("ModelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int C_ModelID {
            get {
                return this.c_ModelIDField;
            }
            set {
                this.c_ModelIDField = value;
                this.RaisePropertyChanged("C_ModelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string MakeDisplay {
            get {
                return this.makeDisplayField;
            }
            set {
                this.makeDisplayField = value;
                this.RaisePropertyChanged("MakeDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ModelDisplay {
            get {
                return this.modelDisplayField;
            }
            set {
                this.modelDisplayField = value;
                this.RaisePropertyChanged("ModelDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TrimDisplay {
            get {
                return this.trimDisplayField;
            }
            set {
                this.trimDisplayField = value;
                this.RaisePropertyChanged("TrimDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=15)]
        public UsedCarOptions[] UsedCarOptions {
            get {
                return this.usedCarOptionsField;
            }
            set {
                this.usedCarOptionsField = value;
                this.RaisePropertyChanged("UsedCarOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int MSRP {
            get {
                return this.mSRPField;
            }
            set {
                this.mSRPField = value;
                this.RaisePropertyChanged("MSRP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int AverageRetailPrice {
            get {
                return this.averageRetailPriceField;
            }
            set {
                this.averageRetailPriceField = value;
                this.RaisePropertyChanged("AverageRetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int AverageTradeinPrice {
            get {
                return this.averageTradeinPriceField;
            }
            set {
                this.averageTradeinPriceField = value;
                this.RaisePropertyChanged("AverageTradeinPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceMinMax : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int minField;
        
        private int maxField;
        
        private MinMaxType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("Max");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MinMaxType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public enum MinMaxType {
        
        /// <remarks/>
        MSRP,
        
        /// <remarks/>
        AverageRetailPrice,
        
        /// <remarks/>
        AverageTradeInPrice,
        
        /// <remarks/>
        HighRetailPrice,
        
        /// <remarks/>
        LowRetailPrice,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceMinMaxCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PriceMinMax[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public PriceMinMax[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarResultSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool hasErrorField;
        
        private ErrorProfile errorField;
        
        private PriceMinMaxCollection priceMinMaxField;
        
        private string[] styleIDsField;
        
        private System.Guid transactionIDField;
        
        private UsedCar[] usedCarsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
                this.RaisePropertyChanged("HasError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PriceMinMaxCollection PriceMinMax {
            get {
                return this.priceMinMaxField;
            }
            set {
                this.priceMinMaxField = value;
                this.RaisePropertyChanged("PriceMinMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StyleIDs", Order=3)]
        public string[] StyleIDs {
            get {
                return this.styleIDsField;
            }
            set {
                this.styleIDsField = value;
                this.RaisePropertyChanged("StyleIDs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Guid TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsedCars", Order=5)]
        public UsedCar[] UsedCars {
            get {
                return this.usedCarsField;
            }
            set {
                this.usedCarsField = value;
                this.RaisePropertyChanged("UsedCars");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class ErrorProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class MileageAdjustment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actualMileageField;
        
        private int adjustmentAmountField;
        
        private string acceptableRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ActualMileage {
            get {
                return this.actualMileageField;
            }
            set {
                this.actualMileageField = value;
                this.RaisePropertyChanged("ActualMileage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AdjustmentAmount {
            get {
                return this.adjustmentAmountField;
            }
            set {
                this.adjustmentAmountField = value;
                this.RaisePropertyChanged("AdjustmentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AcceptableRange {
            get {
                return this.acceptableRangeField;
            }
            set {
                this.acceptableRangeField = value;
                this.RaisePropertyChanged("AcceptableRange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class pricing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int priceTypeIDField;
        
        private string priceTypeField;
        
        private string priceTypeDisplayField;
        
        private int priceField;
        
        private string priceTypeExplanationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
                this.RaisePropertyChanged("PriceTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
                this.RaisePropertyChanged("PriceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
                this.RaisePropertyChanged("PriceTypeDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PriceTypeExplanation {
            get {
                return this.priceTypeExplanationField;
            }
            set {
                this.priceTypeExplanationField = value;
                this.RaisePropertyChanged("PriceTypeExplanation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class Option : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isPercentField;
        
        private int priceTypeIDField;
        
        private string priceTypeField;
        
        private string priceTypeDisplayField;
        
        private int priceField;
        
        private int optionIDField;
        
        private string optionNameField;
        
        private string optionDisplayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsPercent {
            get {
                return this.isPercentField;
            }
            set {
                this.isPercentField = value;
                this.RaisePropertyChanged("IsPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
                this.RaisePropertyChanged("PriceTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
                this.RaisePropertyChanged("PriceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
                this.RaisePropertyChanged("PriceTypeDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
                this.RaisePropertyChanged("OptionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OptionName {
            get {
                return this.optionNameField;
            }
            set {
                this.optionNameField = value;
                this.RaisePropertyChanged("OptionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OptionDisplay {
            get {
                return this.optionDisplayField;
            }
            set {
                this.optionDisplayField = value;
                this.RaisePropertyChanged("OptionDisplay");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceTypeTotal : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string priceTypeIDField;
        
        private string priceTypeDisplayField;
        
        private int totalValueField;
        
        private int totalOptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
                this.RaisePropertyChanged("PriceTypeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
                this.RaisePropertyChanged("PriceTypeDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TotalValue {
            get {
                return this.totalValueField;
            }
            set {
                this.totalValueField = value;
                this.RaisePropertyChanged("TotalValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalOption {
            get {
                return this.totalOptionField;
            }
            set {
                this.totalOptionField = value;
                this.RaisePropertyChanged("TotalOption");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool hasErrorField;
        
        private System.Xml.XmlNode messageField;
        
        private PriceTypeTotal[] usedValueTotalField;
        
        private Option[] usedValueOptionsField;
        
        private pricing[] basePriceField;
        
        private MileageAdjustment usedValueMileageField;
        
        private string transactionIDField;
        
        private string makeDisplayField;
        
        private string modelDisplayField;
        
        private int yearField;
        
        private string trimDisplayField;
        
        private ErrorProfile errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
                this.RaisePropertyChanged("HasError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlNode Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public PriceTypeTotal[] UsedValueTotal {
            get {
                return this.usedValueTotalField;
            }
            set {
                this.usedValueTotalField = value;
                this.RaisePropertyChanged("UsedValueTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Option[] UsedValueOptions {
            get {
                return this.usedValueOptionsField;
            }
            set {
                this.usedValueOptionsField = value;
                this.RaisePropertyChanged("UsedValueOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public pricing[] BasePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
                this.RaisePropertyChanged("BasePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public MileageAdjustment UsedValueMileage {
            get {
                return this.usedValueMileageField;
            }
            set {
                this.usedValueMileageField = value;
                this.RaisePropertyChanged("UsedValueMileage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MakeDisplay {
            get {
                return this.makeDisplayField;
            }
            set {
                this.makeDisplayField = value;
                this.RaisePropertyChanged("MakeDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ModelDisplay {
            get {
                return this.modelDisplayField;
            }
            set {
                this.modelDisplayField = value;
                this.RaisePropertyChanged("ModelDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TrimDisplay {
            get {
                return this.trimDisplayField;
            }
            set {
                this.trimDisplayField = value;
                this.RaisePropertyChanged("TrimDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.517")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarValueOption : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIDField;
        
        private ErrorProfile errorField;
        
        private UsedCarValue computedValueField;
        
        private UsedCarOptions[] availableOptionsField;
        
        private bool hasErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UsedCarValue ComputedValue {
            get {
                return this.computedValueField;
            }
            set {
                this.computedValueField = value;
                this.RaisePropertyChanged("ComputedValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public UsedCarOptions[] AvailableOptions {
            get {
                return this.availableOptionsField;
            }
            set {
                this.availableOptionsField = value;
                this.RaisePropertyChanged("AvailableOptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
                this.RaisePropertyChanged("HasError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsedCarsSoapChannel : NadaScheduler.NadaUsedCars.UsedCarsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsedCarsSoapClient : System.ServiceModel.ClientBase<NadaScheduler.NadaUsedCars.UsedCarsSoap>, NadaScheduler.NadaUsedCars.UsedCarsSoap {
        
        public UsedCarsSoapClient() {
        }
        
        public UsedCarsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsedCarsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsedCarsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsedCarsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NadaScheduler.NadaUsedCars.UsedCarOptionList GetUsedCarOptionsTyped(string UserID, string Password, string StyleID) {
            return base.Channel.GetUsedCarOptionsTyped(UserID, Password, StyleID);
        }
        
        public NadaScheduler.NadaUsedCars.UsedCarValueOption GetUsedCarValueTypedwithOptions(string UserID, string Password, string StyleID, string options, string mileage) {
            return base.Channel.GetUsedCarValueTypedwithOptions(UserID, Password, StyleID, options, mileage);
        }
        
        public NadaScheduler.NadaUsedCars.UsedCarValue GetUsedCarValueTyped(string UserID, string Password, string StyleID, string options, string mileage) {
            return base.Channel.GetUsedCarValueTyped(UserID, Password, StyleID, options, mileage);
        }
        
        public System.Xml.XmlNode GetUsedCarOptions(string UserID, string Password, string StyleID) {
            return base.Channel.GetUsedCarOptions(UserID, Password, StyleID);
        }
        
        public System.Xml.XmlNode GetUsedCarValue(string UserID, string Password, string StyleID, string Options, string Mileage) {
            return base.Channel.GetUsedCarValue(UserID, Password, StyleID, Options, Mileage);
        }
        
        public NadaScheduler.NadaUsedCars.UsedCarResultSet GetUsedCars(string UserName, string Password, string VIN) {
            return base.Channel.GetUsedCars(UserName, Password, VIN);
        }
        
        public NadaScheduler.NadaUsedCars.UsedCarResultSet GetUsedCarsNoVIN(string UserName, string Password, string NewCarStyleIDs) {
            return base.Channel.GetUsedCarsNoVIN(UserName, Password, NewCarStyleIDs);
        }
    }
}
