CREATE TABLE [dbo].[ED_ProductData] (
    [VIN]                 VARCHAR (100)  NOT NULL,
    [CustomerID]          INT            NOT NULL,
    [VehicleName]         VARCHAR (MAX)  NULL,
    [Type]                VARCHAR (MAX)  NULL,
    [TypeAttribute]       INT            NULL,
    [Stock]               VARCHAR (MAX)  NULL,
    [Year]                VARCHAR (MAX)  NULL,
    [YearAttribute]       INT            NULL,
    [Make]                VARCHAR (MAX)  NULL,
    [MakeAttribute]       INT            NULL,
    [Model]               VARCHAR (MAX)  NULL,
    [Trim]                VARCHAR (MAX)  NULL,
    [Free_Text]           VARCHAR (MAX)  NULL,
    [Body]                VARCHAR (MAX)  NULL,
    [BodyAttribute]       INT            NULL,
    [Mileage]             VARCHAR (MAX)  NULL,
    [MileageAttribute]    INT            NULL,
    [Price_Current]       MONEY          NULL,
    [Reserved]            VARCHAR (MAX)  NULL,
    [Price_Wholesale]     MONEY          NULL,
    [Price_Cost]          MONEY          NULL,
    [PriceAttribute]      INT            NULL,
    [Title]               VARCHAR (MAX)  NULL,
    [Condition]           VARCHAR (MAX)  NULL,
    [Exterior_Color]      VARCHAR (MAX)  NULL,
    [Interior_Color]      VARCHAR (MAX)  NULL,
    [Doors]               VARCHAR (MAX)  NULL,
    [Engine]              VARCHAR (MAX)  NULL,
    [Transmission]        VARCHAR (MAX)  NULL,
    [Fuel_Type]           VARCHAR (MAX)  NULL,
    [Drive_Type]          VARCHAR (MAX)  NULL,
    [Options]             VARCHAR (MAX)  NULL,
    [Warranty]            VARCHAR (MAX)  NULL,
    [WarrantyAttribute]   INT            NULL,
    [Description]         VARCHAR (MAX)  NULL,
    [Pics]                VARCHAR (MAX)  NULL,
    [Date_in_Stock]       VARCHAR (MAX)  NULL,
    [CreatedOn]           DATETIME       NULL,
    [ParaId]              INT            NULL,
    [FileName]            VARCHAR (MAX)  NULL,
    [Dealer_Name]         NVARCHAR (MAX) NULL,
    [Dealer_Zip]          NVARCHAR (MAX) NULL,
    [City]                NVARCHAR (MAX) NULL,
    [StateID]             INT            NULL,
    [AverageRetailPrice]  MONEY          NULL,
    [AverageTradeinPrice] MONEY          NULL,
    [City_Fuel]           INT            NULL,
    [Highway_Fuel]        INT            NULL
);

