CREATE TABLE [dbo].[Nop_Product] (
    [ProductId]            INT             IDENTITY (1, 1) NOT NULL,
    [Name]                 NVARCHAR (400)  NOT NULL,
    [ShortDescription]     NVARCHAR (MAX)  NOT NULL,
    [FullDescription]      NVARCHAR (MAX)  NOT NULL,
    [AdminComment]         NVARCHAR (MAX)  NOT NULL,
    [ProductTypeID]        INT             NOT NULL,
    [TemplateID]           INT             NOT NULL,
    [ShowOnHomePage]       BIT             NOT NULL,
    [MetaKeywords]         NVARCHAR (400)  NOT NULL,
    [MetaDescription]      NVARCHAR (4000) NOT NULL,
    [MetaTitle]            NVARCHAR (400)  NOT NULL,
    [SEName]               NVARCHAR (100)  NOT NULL,
    [AllowCustomerReviews] BIT             NOT NULL,
    [AllowCustomerRatings] BIT             NOT NULL,
    [RatingSum]            INT             NOT NULL,
    [TotalRatingVotes]     INT             NOT NULL,
    [Published]            BIT             NOT NULL,
    [Deleted]              BIT             NOT NULL,
    [CreatedOn]            DATETIME        NOT NULL,
    [UpdatedOn]            DATETIME        NOT NULL,
    [VIN]                  NVARCHAR (100)  NULL,
    [CustomerID]           INT             NULL,
    [VehicleName]          NVARCHAR (250)  NULL,
    [Type]                 NVARCHAR (50)   NULL,
    [TypeAttribute]        INT             NULL,
    [Stock]                NVARCHAR (50)   NULL,
    [Year]                 NVARCHAR (50)   NULL,
    [YearAttribute]        INT             NULL,
    [Make]                 NVARCHAR (50)   NULL,
    [MakeAttribute]        INT             NULL,
    [Model]                NVARCHAR (50)   NULL,
    [Trim]                 NVARCHAR (50)   NULL,
    [Free_Text]            NVARCHAR (MAX)  NULL,
    [Body]                 NVARCHAR (50)   NULL,
    [BodyAttribute]        INT             NULL,
    [Mileage]              NVARCHAR (50)   NULL,
    [MileageAttribute]     INT             NULL,
    [Price_Current]        MONEY           NULL,
    [Reserved]             NVARCHAR (50)   NULL,
    [Price_Wholesale]      MONEY           NULL,
    [Price_Cost]           MONEY           NULL,
    [PriceAttribute]       INT             NULL,
    [Title]                NVARCHAR (50)   NULL,
    [Condition]            NVARCHAR (50)   NULL,
    [Exterior_Color]       NVARCHAR (50)   NULL,
    [Interior_Color]       NVARCHAR (50)   NULL,
    [Doors]                NVARCHAR (50)   NULL,
    [Engine]               NVARCHAR (50)   NULL,
    [Transmission]         NVARCHAR (50)   NULL,
    [Fuel_Type]            NVARCHAR (50)   NULL,
    [Drive_Type]           NVARCHAR (50)   NULL,
    [Options]              NVARCHAR (MAX)  NULL,
    [Warranty]             NVARCHAR (50)   NULL,
    [WarrantyAttribute]    INT             NULL,
    [Description]          NVARCHAR (MAX)  NULL,
    [Pics]                 NVARCHAR (MAX)  NULL,
    [Date_in_Stock]        DATETIME        NULL,
    [FileName]             NVARCHAR (MAX)  NULL,
    [IsNew]                BIT             NULL,
    [IsFeature]            BIT             NULL,
    [Dealer_Name]          NVARCHAR (MAX)  NULL,
    [Dealer_Zip]           NVARCHAR (MAX)  NULL,
    [SavingAmount]         MONEY           NULL,
    [City]                 NVARCHAR (MAX)  NULL,
    [StateID]              INT             NULL,
    [QualifyPrice]         MONEY           NULL,
    [OwnerDetail]          VARCHAR (500)   NULL,
    [Show_on_Dealer]       BIT             NULL,
    [Offer]                BIT             NULL,
    [AverageRetailPrice]   MONEY           NULL,
    [AverageTradeinPrice]  MONEY           NULL,
    [City_Fuel]            INT             NULL,
    [Highway_Fuel]         INT             NULL,
    [SellerEmail]          NVARCHAR (150)  NULL,
    [SellerName]           NVARCHAR (150)  NULL,
    [SellerPhone]          NVARCHAR (150)  NULL,
    [SellerNotes]          NVARCHAR (MAX)  NULL
);

