//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Web.Mvc;
using Edrive.Edrivie_Service_Ref;
using Edrive.Models;

namespace Edrive.Search_ref {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products", Namespace="http://schemas.datacontract.org/2004/07/EdriveService.DataContract")]
    [Serializable()]
    public partial class Products : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowOnDealerProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal averageRetailPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal averageTradeinPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int city_FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createdOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int customerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_in_StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool deletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptiontField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int doorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string drive_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string engineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string exteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string free_TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fuel_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int highWay_FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string interiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isfeatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string optionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string picsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal price_CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal price_CurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal price_WholeSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool publishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal qualifyPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal savingAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transmissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string trimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime updatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool warrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeName {
            get {
                return this.MakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNameField, value) != true)) {
                    this.MakeNameField = value;
                    this.RaisePropertyChanged("MakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerDetail {
            get {
                return this.OwnerDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerDetailField, value) != true)) {
                    this.OwnerDetailField = value;
                    this.RaisePropertyChanged("OwnerDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reserved {
            get {
                return this.ReservedField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservedField, value) != true)) {
                    this.ReservedField = value;
                    this.RaisePropertyChanged("Reserved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowOnDealerProfile {
            get {
                return this.ShowOnDealerProfileField;
            }
            set {
                if ((this.ShowOnDealerProfileField.Equals(value) != true)) {
                    this.ShowOnDealerProfileField = value;
                    this.RaisePropertyChanged("ShowOnDealerProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal averageRetailPrice {
            get {
                return this.averageRetailPriceField;
            }
            set {
                if ((this.averageRetailPriceField.Equals(value) != true)) {
                    this.averageRetailPriceField = value;
                    this.RaisePropertyChanged("averageRetailPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal averageTradeinPrice {
            get {
                return this.averageTradeinPriceField;
            }
            set {
                if ((this.averageTradeinPriceField.Equals(value) != true)) {
                    this.averageTradeinPriceField = value;
                    this.RaisePropertyChanged("averageTradeinPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                if ((object.ReferenceEquals(this.bodyField, value) != true)) {
                    this.bodyField = value;
                    this.RaisePropertyChanged("body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int city_Fuel {
            get {
                return this.city_FuelField;
            }
            set {
                if ((this.city_FuelField.Equals(value) != true)) {
                    this.city_FuelField = value;
                    this.RaisePropertyChanged("city_Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                if ((object.ReferenceEquals(this.conditionField, value) != true)) {
                    this.conditionField = value;
                    this.RaisePropertyChanged("condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createdOn {
            get {
                return this.createdOnField;
            }
            set {
                if ((this.createdOnField.Equals(value) != true)) {
                    this.createdOnField = value;
                    this.RaisePropertyChanged("createdOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                if ((this.customerIdField.Equals(value) != true)) {
                    this.customerIdField = value;
                    this.RaisePropertyChanged("customerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_in_Stock {
            get {
                return this.date_in_StockField;
            }
            set {
                if ((this.date_in_StockField.Equals(value) != true)) {
                    this.date_in_StockField = value;
                    this.RaisePropertyChanged("date_in_Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                if ((this.deletedField.Equals(value) != true)) {
                    this.deletedField = value;
                    this.RaisePropertyChanged("deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descriptiont {
            get {
                return this.descriptiontField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptiontField, value) != true)) {
                    this.descriptiontField = value;
                    this.RaisePropertyChanged("descriptiont");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int doors {
            get {
                return this.doorsField;
            }
            set {
                if ((this.doorsField.Equals(value) != true)) {
                    this.doorsField = value;
                    this.RaisePropertyChanged("doors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string drive_Type {
            get {
                return this.drive_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.drive_TypeField, value) != true)) {
                    this.drive_TypeField = value;
                    this.RaisePropertyChanged("drive_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string engine {
            get {
                return this.engineField;
            }
            set {
                if ((object.ReferenceEquals(this.engineField, value) != true)) {
                    this.engineField = value;
                    this.RaisePropertyChanged("engine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string exterior {
            get {
                return this.exteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.exteriorField, value) != true)) {
                    this.exteriorField = value;
                    this.RaisePropertyChanged("exterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string free_Text {
            get {
                return this.free_TextField;
            }
            set {
                if ((object.ReferenceEquals(this.free_TextField, value) != true)) {
                    this.free_TextField = value;
                    this.RaisePropertyChanged("free_Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fuel_Type {
            get {
                return this.fuel_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.fuel_TypeField, value) != true)) {
                    this.fuel_TypeField = value;
                    this.RaisePropertyChanged("fuel_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int highWay_Fuel {
            get {
                return this.highWay_FuelField;
            }
            set {
                if ((this.highWay_FuelField.Equals(value) != true)) {
                    this.highWay_FuelField = value;
                    this.RaisePropertyChanged("highWay_Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string interior {
            get {
                return this.interiorField;
            }
            set {
                if ((object.ReferenceEquals(this.interiorField, value) != true)) {
                    this.interiorField = value;
                    this.RaisePropertyChanged("interior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNew {
            get {
                return this.isNewField;
            }
            set {
                if ((this.isNewField.Equals(value) != true)) {
                    this.isNewField = value;
                    this.RaisePropertyChanged("isNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isfeature {
            get {
                return this.isfeatureField;
            }
            set {
                if ((this.isfeatureField.Equals(value) != true)) {
                    this.isfeatureField = value;
                    this.RaisePropertyChanged("isfeature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mileage {
            get {
                return this.mileageField;
            }
            set {
                if ((this.mileageField.Equals(value) != true)) {
                    this.mileageField = value;
                    this.RaisePropertyChanged("mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int model {
            get {
                return this.modelField;
            }
            set {
                if ((this.modelField.Equals(value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string options {
            get {
                return this.optionsField;
            }
            set {
                if ((object.ReferenceEquals(this.optionsField, value) != true)) {
                    this.optionsField = value;
                    this.RaisePropertyChanged("options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pics {
            get {
                return this.picsField;
            }
            set {
                if ((object.ReferenceEquals(this.picsField, value) != true)) {
                    this.picsField = value;
                    this.RaisePropertyChanged("pics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price_Cost {
            get {
                return this.price_CostField;
            }
            set {
                if ((this.price_CostField.Equals(value) != true)) {
                    this.price_CostField = value;
                    this.RaisePropertyChanged("price_Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price_Current {
            get {
                return this.price_CurrentField;
            }
            set {
                if ((this.price_CurrentField.Equals(value) != true)) {
                    this.price_CurrentField = value;
                    this.RaisePropertyChanged("price_Current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price_WholeSale {
            get {
                return this.price_WholeSaleField;
            }
            set {
                if ((this.price_WholeSaleField.Equals(value) != true)) {
                    this.price_WholeSaleField = value;
                    this.RaisePropertyChanged("price_WholeSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool published {
            get {
                return this.publishedField;
            }
            set {
                if ((this.publishedField.Equals(value) != true)) {
                    this.publishedField = value;
                    this.RaisePropertyChanged("published");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal qualifyPrice {
            get {
                return this.qualifyPriceField;
            }
            set {
                if ((this.qualifyPriceField.Equals(value) != true)) {
                    this.qualifyPriceField = value;
                    this.RaisePropertyChanged("qualifyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal savingAmount {
            get {
                return this.savingAmountField;
            }
            set {
                if ((this.savingAmountField.Equals(value) != true)) {
                    this.savingAmountField = value;
                    this.RaisePropertyChanged("savingAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stateID {
            get {
                return this.stateIDField;
            }
            set {
                if ((this.stateIDField.Equals(value) != true)) {
                    this.stateIDField = value;
                    this.RaisePropertyChanged("stateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stock {
            get {
                return this.stockField;
            }
            set {
                if ((object.ReferenceEquals(this.stockField, value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transmission {
            get {
                return this.transmissionField;
            }
            set {
                if ((object.ReferenceEquals(this.transmissionField, value) != true)) {
                    this.transmissionField = value;
                    this.RaisePropertyChanged("transmission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trim {
            get {
                return this.trimField;
            }
            set {
                if ((object.ReferenceEquals(this.trimField, value) != true)) {
                    this.trimField = value;
                    this.RaisePropertyChanged("trim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime updatedOn {
            get {
                return this.updatedOnField;
            }
            set {
                if ((this.updatedOnField.Equals(value) != true)) {
                    this.updatedOnField = value;
                    this.RaisePropertyChanged("updatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vehicleName {
            get {
                return this.vehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleNameField, value) != true)) {
                    this.vehicleNameField = value;
                    this.RaisePropertyChanged("vehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                if ((object.ReferenceEquals(this.vinField, value) != true)) {
                    this.vinField = value;
                    this.RaisePropertyChanged("vin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool warranty {
            get {
                return this.warrantyField;
            }
            set {
                if ((this.warrantyField.Equals(value) != true)) {
                    this.warrantyField = value;
                    this.RaisePropertyChanged("warranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zip {
            get {
                return this.zipField;
            }
            set {
                if ((this.zipField.Equals(value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Search_ref.ISearch")]
    public interface ISearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearch/SearchProductBy_Make_Model_City_Zip", ReplyAction="http://tempuri.org/ISearch/SearchProductBy_Make_Model_City_ZipResponse")]
        Edrive.Search_ref.Products[] SearchProductBy_Make_Model_City_Zip(
                    string searchKey, 
                    int pageSize, 
                    int pageIndex, 
                    ref System.Nullable<int> CarsCount, 
                    string SortByColumn, 
                    ref string Price, 
                    ref string Milage, 
                    ref string Make, 
                    ref string ModelID, 
                    ref string Year, 
                    ref string Body, 
                    ref string Type, 
                    int Zip, 
                    string Warranty, 
                    ref string Vin, 
                    string Transmission, 
                    string Engine, 
                    ref string DriveType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchChannel : Edrive.Search_ref.ISearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchClient : System.ServiceModel.ClientBase<Edrive.Search_ref.ISearch>, Edrive.Search_ref.ISearch {
        
        public SearchClient() {
        }
        
        public SearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Edrive.Search_ref.Products[] SearchProductBy_Make_Model_City_Zip(
                    string searchKey, 
                    int pageSize, 
                    int pageIndex, 
                    ref System.Nullable<int> CarsCount, 
                    string SortByColumn, 
                    ref string Price, 
                    ref string Milage, 
                    ref string Make, 
                    ref string ModelID, 
                    ref string Year, 
                    ref string Body, 
                    ref string Type, 
                    int Zip, 
                    string Warranty, 
                    ref string Vin, 
                    string Transmission, 
                    string Engine, 
                    ref string DriveType) {
            return base.Channel.SearchProductBy_Make_Model_City_Zip(searchKey, pageSize, pageIndex, ref CarsCount, SortByColumn, ref Price, ref Milage, ref Make, ref ModelID, ref Year, ref Body, ref Type, Zip, Warranty, ref Vin, Transmission, Engine, ref DriveType);
        }
    }
}
