//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 

using System;
using System.Linq;

#pragma warning disable 1591

namespace EdriveService.Nada_UsedCarPrices {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsedCarPricesSoap", Namespace="http://UsedCar.NADAguides.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnObject))]
    public partial class UsedCarPrices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUsedCarOptionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsedCarValuesWithMileageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMakesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetModelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetYearsForMakeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStylesForModelOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStyleInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsedCarPrices() {
            this.Url = global::EdriveService.Properties.Settings.Default.EdriveService_Nada_UsedCarPrices_UsedCarPrices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUsedCarOptionsCompletedEventHandler GetUsedCarOptionsCompleted;
        
        /// <remarks/>
        public event GetUsedCarValuesCompletedEventHandler GetUsedCarValuesCompleted;
        
        /// <remarks/>
        public event GetUsedCarValuesWithMileageCompletedEventHandler GetUsedCarValuesWithMileageCompleted;
        
        /// <remarks/>
        public event GetAllMakesCompletedEventHandler GetAllMakesCompleted;
        
        /// <remarks/>
        public event GetModelsCompletedEventHandler GetModelsCompleted;
        
        /// <remarks/>
        public event GetYearsForMakeCompletedEventHandler GetYearsForMakeCompleted;
        
        /// <remarks/>
        public event GetStylesForModelCompletedEventHandler GetStylesForModelCompleted;
        
        /// <remarks/>
        public event GetStyleInfoCompletedEventHandler GetStyleInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarOptions", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataObject GetUsedCarOptions(string UserID, string Password, int UsedStyleID) {
            object[] results = this.Invoke("GetUsedCarOptions", new object[] {
                        UserID,
                        Password,
                        UsedStyleID});
            return ((DataObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarOptionsAsync(string UserID, string Password, int UsedStyleID) {
            this.GetUsedCarOptionsAsync(UserID, Password, UsedStyleID, null);
        }
        
        /// <remarks/>
        public void GetUsedCarOptionsAsync(string UserID, string Password, int UsedStyleID, object userState) {
            if ((this.GetUsedCarOptionsOperationCompleted == null)) {
                this.GetUsedCarOptionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarOptionsOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarOptions", new object[] {
                        UserID,
                        Password,
                        UsedStyleID}, this.GetUsedCarOptionsOperationCompleted, userState);
        }
        
        private void OnGetUsedCarOptionsOperationCompleted(object arg) {
            if ((this.GetUsedCarOptionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarOptionsCompleted(this, new GetUsedCarOptionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarValues", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarValue GetUsedCarValues(string UserID, string Password, int UsedStyleID, string Options) {
            object[] results = this.Invoke("GetUsedCarValues", new object[] {
                        UserID,
                        Password,
                        UsedStyleID,
                        Options});
            return ((UsedCarValue)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarValuesAsync(string UserID, string Password, int UsedStyleID, string Options) {
            this.GetUsedCarValuesAsync(UserID, Password, UsedStyleID, Options, null);
        }
        
        /// <remarks/>
        public void GetUsedCarValuesAsync(string UserID, string Password, int UsedStyleID, string Options, object userState) {
            if ((this.GetUsedCarValuesOperationCompleted == null)) {
                this.GetUsedCarValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarValuesOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarValues", new object[] {
                        UserID,
                        Password,
                        UsedStyleID,
                        Options}, this.GetUsedCarValuesOperationCompleted, userState);
        }
        
        private void OnGetUsedCarValuesOperationCompleted(object arg) {
            if ((this.GetUsedCarValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarValuesCompleted(this, new GetUsedCarValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetUsedCarValuesWithMileage", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UsedCarValue GetUsedCarValuesWithMileage(string UserID, string Password, int UsedStyleID, string Options, string Mileage) {
            object[] results = this.Invoke("GetUsedCarValuesWithMileage", new object[] {
                        UserID,
                        Password,
                        UsedStyleID,
                        Options,
                        Mileage});
            return ((UsedCarValue)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsedCarValuesWithMileageAsync(string UserID, string Password, int UsedStyleID, string Options, string Mileage) {
            this.GetUsedCarValuesWithMileageAsync(UserID, Password, UsedStyleID, Options, Mileage, null);
        }
        
        /// <remarks/>
        public void GetUsedCarValuesWithMileageAsync(string UserID, string Password, int UsedStyleID, string Options, string Mileage, object userState) {
            if ((this.GetUsedCarValuesWithMileageOperationCompleted == null)) {
                this.GetUsedCarValuesWithMileageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsedCarValuesWithMileageOperationCompleted);
            }
            this.InvokeAsync("GetUsedCarValuesWithMileage", new object[] {
                        UserID,
                        Password,
                        UsedStyleID,
                        Options,
                        Mileage}, this.GetUsedCarValuesWithMileageOperationCompleted, userState);
        }
        
        private void OnGetUsedCarValuesWithMileageOperationCompleted(object arg) {
            if ((this.GetUsedCarValuesWithMileageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsedCarValuesWithMileageCompleted(this, new GetUsedCarValuesWithMileageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetAllMakes", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataObject GetAllMakes(string UserID, string Password) {
            object[] results = this.Invoke("GetAllMakes", new object[] {
                        UserID,
                        Password});
            return ((DataObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMakesAsync(string UserID, string Password) {
            this.GetAllMakesAsync(UserID, Password, null);
        }
        
        /// <remarks/>
        public void GetAllMakesAsync(string UserID, string Password, object userState) {
            if ((this.GetAllMakesOperationCompleted == null)) {
                this.GetAllMakesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMakesOperationCompleted);
            }
            this.InvokeAsync("GetAllMakes", new object[] {
                        UserID,
                        Password}, this.GetAllMakesOperationCompleted, userState);
        }
        
        private void OnGetAllMakesOperationCompleted(object arg) {
            if ((this.GetAllMakesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMakesCompleted(this, new GetAllMakesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetModels", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataObject GetModels(string UserID, string Password, int MakeID, int Year) {
            object[] results = this.Invoke("GetModels", new object[] {
                        UserID,
                        Password,
                        MakeID,
                        Year});
            return ((DataObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetModelsAsync(string UserID, string Password, int MakeID, int Year) {
            this.GetModelsAsync(UserID, Password, MakeID, Year, null);
        }
        
        /// <remarks/>
        public void GetModelsAsync(string UserID, string Password, int MakeID, int Year, object userState) {
            if ((this.GetModelsOperationCompleted == null)) {
                this.GetModelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModelsOperationCompleted);
            }
            this.InvokeAsync("GetModels", new object[] {
                        UserID,
                        Password,
                        MakeID,
                        Year}, this.GetModelsOperationCompleted, userState);
        }
        
        private void OnGetModelsOperationCompleted(object arg) {
            if ((this.GetModelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModelsCompleted(this, new GetModelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetYearsForMake", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataObject GetYearsForMake(string UserID, string Password, int MakeID) {
            object[] results = this.Invoke("GetYearsForMake", new object[] {
                        UserID,
                        Password,
                        MakeID});
            return ((DataObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetYearsForMakeAsync(string UserID, string Password, int MakeID) {
            this.GetYearsForMakeAsync(UserID, Password, MakeID, null);
        }
        
        /// <remarks/>
        public void GetYearsForMakeAsync(string UserID, string Password, int MakeID, object userState) {
            if ((this.GetYearsForMakeOperationCompleted == null)) {
                this.GetYearsForMakeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetYearsForMakeOperationCompleted);
            }
            this.InvokeAsync("GetYearsForMake", new object[] {
                        UserID,
                        Password,
                        MakeID}, this.GetYearsForMakeOperationCompleted, userState);
        }
        
        private void OnGetYearsForMakeOperationCompleted(object arg) {
            if ((this.GetYearsForMakeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetYearsForMakeCompleted(this, new GetYearsForMakeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetStylesForModel", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataObject GetStylesForModel(string UserID, string Password, int ModelID) {
            object[] results = this.Invoke("GetStylesForModel", new object[] {
                        UserID,
                        Password,
                        ModelID});
            return ((DataObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetStylesForModelAsync(string UserID, string Password, int ModelID) {
            this.GetStylesForModelAsync(UserID, Password, ModelID, null);
        }
        
        /// <remarks/>
        public void GetStylesForModelAsync(string UserID, string Password, int ModelID, object userState) {
            if ((this.GetStylesForModelOperationCompleted == null)) {
                this.GetStylesForModelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStylesForModelOperationCompleted);
            }
            this.InvokeAsync("GetStylesForModel", new object[] {
                        UserID,
                        Password,
                        ModelID}, this.GetStylesForModelOperationCompleted, userState);
        }
        
        private void OnGetStylesForModelOperationCompleted(object arg) {
            if ((this.GetStylesForModelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStylesForModelCompleted(this, new GetStylesForModelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://UsedCar.NADAguides.com/GetStyleInfo", RequestNamespace="http://UsedCar.NADAguides.com", ResponseNamespace="http://UsedCar.NADAguides.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataObject GetStyleInfo(string UserID, string Password, int StyleID) {
            object[] results = this.Invoke("GetStyleInfo", new object[] {
                        UserID,
                        Password,
                        StyleID});
            return ((DataObject)(results[0]));
        }
        
        /// <remarks/>
        public void GetStyleInfoAsync(string UserID, string Password, int StyleID) {
            this.GetStyleInfoAsync(UserID, Password, StyleID, null);
        }
        
        /// <remarks/>
        public void GetStyleInfoAsync(string UserID, string Password, int StyleID, object userState) {
            if ((this.GetStyleInfoOperationCompleted == null)) {
                this.GetStyleInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStyleInfoOperationCompleted);
            }
            this.InvokeAsync("GetStyleInfo", new object[] {
                        UserID,
                        Password,
                        StyleID}, this.GetStyleInfoOperationCompleted, userState);
        }
        
        private void OnGetStyleInfoOperationCompleted(object arg) {
            if ((this.GetStyleInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStyleInfoCompleted(this, new GetStyleInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class DataObject : ReturnObject {
        
        private System.Data.DataSet getDataField;
        
        /// <remarks/>
        public System.Data.DataSet GetData {
            get {
                return this.getDataField;
            }
            set {
                this.getDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OptionsWrapper))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class ReturnObject {
        
        private bool hasErrorField;
        
        private ErrorProfile errorField;
        
        private System.Guid transactionIDField;
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class ErrorProfile {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class MileageAdjustment {
        
        private string actualMileageField;
        
        private int adjustmentAmountField;
        
        private string acceptableRangeField;
        
        /// <remarks/>
        public string ActualMileage {
            get {
                return this.actualMileageField;
            }
            set {
                this.actualMileageField = value;
            }
        }
        
        /// <remarks/>
        public int AdjustmentAmount {
            get {
                return this.adjustmentAmountField;
            }
            set {
                this.adjustmentAmountField = value;
            }
        }
        
        /// <remarks/>
        public string AcceptableRange {
            get {
                return this.acceptableRangeField;
            }
            set {
                this.acceptableRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class pricing {
        
        private int priceTypeIDField;
        
        private string priceTypeField;
        
        private string priceTypeDisplayField;
        
        private int priceField;
        
        private string priceTypeExplanationField;
        
        /// <remarks/>
        public int PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeExplanation {
            get {
                return this.priceTypeExplanationField;
            }
            set {
                this.priceTypeExplanationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class Option {
        
        private bool isPercentField;
        
        private int priceTypeIDField;
        
        private string priceTypeField;
        
        private string priceTypeDisplayField;
        
        private int priceField;
        
        private int optionIDField;
        
        private string optionNameField;
        
        private string optionDisplayField;
        
        /// <remarks/>
        public bool IsPercent {
            get {
                return this.isPercentField;
            }
            set {
                this.isPercentField = value;
            }
        }
        
        /// <remarks/>
        public int PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceType {
            get {
                return this.priceTypeField;
            }
            set {
                this.priceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int OptionID {
            get {
                return this.optionIDField;
            }
            set {
                this.optionIDField = value;
            }
        }
        
        /// <remarks/>
        public string OptionName {
            get {
                return this.optionNameField;
            }
            set {
                this.optionNameField = value;
            }
        }
        
        /// <remarks/>
        public string OptionDisplay {
            get {
                return this.optionDisplayField;
            }
            set {
                this.optionDisplayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class PriceTypeTotal {
        
        private string priceTypeIDField;
        
        private string priceTypeDisplayField;
        
        private int totalValueField;
        
        private int totalOptionField;
        
        /// <remarks/>
        public string PriceTypeID {
            get {
                return this.priceTypeIDField;
            }
            set {
                this.priceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceTypeDisplay {
            get {
                return this.priceTypeDisplayField;
            }
            set {
                this.priceTypeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int TotalValue {
            get {
                return this.totalValueField;
            }
            set {
                this.totalValueField = value;
            }
        }
        
        /// <remarks/>
        public int TotalOption {
            get {
                return this.totalOptionField;
            }
            set {
                this.totalOptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class UsedCarValue {
        
        private bool hasErrorField;
        
        private System.Xml.XmlNode messageField;
        
        private PriceTypeTotal[] usedValueTotalField;
        
        private Option[] usedValueOptionsField;
        
        private pricing[] basePriceField;
        
        private MileageAdjustment usedValueMileageField;
        
        private string transactionIDField;
        
        private string makeDisplayField;
        
        private string modelDisplayField;
        
        private int yearField;
        
        private string trimDisplayField;
        
        private ErrorProfile errorField;
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public PriceTypeTotal[] UsedValueTotal {
            get {
                return this.usedValueTotalField;
            }
            set {
                this.usedValueTotalField = value;
            }
        }
        
        /// <remarks/>
        public Option[] UsedValueOptions {
            get {
                return this.usedValueOptionsField;
            }
            set {
                this.usedValueOptionsField = value;
            }
        }
        
        /// <remarks/>
        public pricing[] BasePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
            }
        }
        
        /// <remarks/>
        public MileageAdjustment UsedValueMileage {
            get {
                return this.usedValueMileageField;
            }
            set {
                this.usedValueMileageField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string MakeDisplay {
            get {
                return this.makeDisplayField;
            }
            set {
                this.makeDisplayField = value;
            }
        }
        
        /// <remarks/>
        public string ModelDisplay {
            get {
                return this.modelDisplayField;
            }
            set {
                this.modelDisplayField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string TrimDisplay {
            get {
                return this.trimDisplayField;
            }
            set {
                this.trimDisplayField = value;
            }
        }
        
        /// <remarks/>
        public ErrorProfile Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class OptionMap {
        
        private string checkedBoxField;
        
        private int indexField;
        
        private string imageField;
        
        private string imageNewField;
        
        private string imageDescriptionField;
        
        private string headerField;
        
        private string shortDescriptionField;
        
        private string descriptionField;
        
        private string optionCodeField;
        
        private string invoiceField;
        
        private string mSRPField;
        
        private string onlyOneinGroupField;
        
        private string inCheckListField;
        
        private string optionKindIdField;
        
        private string locOptionField;
        
        private bool isShowOptionCodeField;
        
        private bool isOptionCheckedField;
        
        private string optionHeaderIdField;
        
        private string oEMOptionCodeField;
        
        private bool isShowCheckBoxField;
        
        private string rgbHexCodeField;
        
        private string isDisplayField;
        
        /// <remarks/>
        public string checkedBox {
            get {
                return this.checkedBoxField;
            }
            set {
                this.checkedBoxField = value;
            }
        }
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public string ImageNew {
            get {
                return this.imageNewField;
            }
            set {
                this.imageNewField = value;
            }
        }
        
        /// <remarks/>
        public string ImageDescription {
            get {
                return this.imageDescriptionField;
            }
            set {
                this.imageDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string ShortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OptionCode {
            get {
                return this.optionCodeField;
            }
            set {
                this.optionCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public string MSRP {
            get {
                return this.mSRPField;
            }
            set {
                this.mSRPField = value;
            }
        }
        
        /// <remarks/>
        public string OnlyOneinGroup {
            get {
                return this.onlyOneinGroupField;
            }
            set {
                this.onlyOneinGroupField = value;
            }
        }
        
        /// <remarks/>
        public string InCheckList {
            get {
                return this.inCheckListField;
            }
            set {
                this.inCheckListField = value;
            }
        }
        
        /// <remarks/>
        public string OptionKindId {
            get {
                return this.optionKindIdField;
            }
            set {
                this.optionKindIdField = value;
            }
        }
        
        /// <remarks/>
        public string LocOption {
            get {
                return this.locOptionField;
            }
            set {
                this.locOptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsShowOptionCode {
            get {
                return this.isShowOptionCodeField;
            }
            set {
                this.isShowOptionCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOptionChecked {
            get {
                return this.isOptionCheckedField;
            }
            set {
                this.isOptionCheckedField = value;
            }
        }
        
        /// <remarks/>
        public string OptionHeaderId {
            get {
                return this.optionHeaderIdField;
            }
            set {
                this.optionHeaderIdField = value;
            }
        }
        
        /// <remarks/>
        public string OEMOptionCode {
            get {
                return this.oEMOptionCodeField;
            }
            set {
                this.oEMOptionCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsShowCheckBox {
            get {
                return this.isShowCheckBoxField;
            }
            set {
                this.isShowCheckBoxField = value;
            }
        }
        
        /// <remarks/>
        public string RgbHexCode {
            get {
                return this.rgbHexCodeField;
            }
            set {
                this.rgbHexCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IsDisplay {
            get {
                return this.isDisplayField;
            }
            set {
                this.isDisplayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class OptionsWrapper : ReturnObject {
        
        private OptionMap[] optionMapsField;
        
        private string serializedOptionStateField;
        
        private int makeIDField;
        
        private int modelIDField;
        
        private int yearField;
        
        /// <remarks/>
        public OptionMap[] OptionMaps {
            get {
                return this.optionMapsField;
            }
            set {
                this.optionMapsField = value;
            }
        }
        
        /// <remarks/>
        public string SerializedOptionState {
            get {
                return this.serializedOptionStateField;
            }
            set {
                this.serializedOptionStateField = value;
            }
        }
        
        /// <remarks/>
        public int MakeID {
            get {
                return this.makeIDField;
            }
            set {
                this.makeIDField = value;
            }
        }
        
        /// <remarks/>
        public int ModelID {
            get {
                return this.modelIDField;
            }
            set {
                this.modelIDField = value;
            }
        }
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://UsedCar.NADAguides.com")]
    public partial class GenericObject : ReturnObject {
        
        private object getDataField;
        
        /// <remarks/>
        public object GetData {
            get {
                return this.getDataField;
            }
            set {
                this.getDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarOptionsCompletedEventHandler(object sender, GetUsedCarOptionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarOptionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarOptionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarValuesCompletedEventHandler(object sender, GetUsedCarValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarValue Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarValue)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUsedCarValuesWithMileageCompletedEventHandler(object sender, GetUsedCarValuesWithMileageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsedCarValuesWithMileageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsedCarValuesWithMileageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UsedCarValue Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UsedCarValue)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllMakesCompletedEventHandler(object sender, GetAllMakesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMakesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMakesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetModelsCompletedEventHandler(object sender, GetModelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetYearsForMakeCompletedEventHandler(object sender, GetYearsForMakeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetYearsForMakeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetYearsForMakeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStylesForModelCompletedEventHandler(object sender, GetStylesForModelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStylesForModelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStylesForModelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStyleInfoCompletedEventHandler(object sender, GetStyleInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStyleInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStyleInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataObject)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591